### ISSUE TITLE
[Deals Page] The table formatting

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#100]
We need to do something about how the tables look like on mobile. It's not clean. 

You can clearly see that there's enough space between the columns for more proper distribution of the text. Especially the column in the middle, which looks like it's shrunk by the other two.

![Screen Shot 2019-03-17 at 18 51 05](https://user-images.githubusercontent.com/39112974/54496436-2f511900-48e7-11e9-991a-e221d4244f82.jpg)

Also, I believe that the table is causing the lateral move in the issue #98

**Comment by lcoenen** [comment]
The table looks fine on my device.

**Comment by RohrerHope** [comment]
@lcoenen 

Can you post a screenshot? :)

**Comment by RohrerHope** [comment]
> The table looks fine on my device.

BTW, If I put my mobile in a horizontal position, that will change the distribution of the table, of course. However, that's not the ideal because most people won't do that. :)

There is a way to make that table respond better to the size of the screen. I saw it with the Google Material elements that you guys shared and that Radu showed me last Friday.

And also in a way that does not generate a lateral scroll on a mobile. :) 

👍🏼

**Comment by buckwierd** [comment]
Fixed and pushed over `set-up-del-pages` @lcoenen @RohrerHope 
<img width="419" alt="Screenshot 2019-03-21 at 18 41 03" src="https://user-images.githubusercontent.com/45966402/54776991-3048ba00-4c09-11e9-8d62-18aab9bbc41c.png">

**Comment by RohrerHope** [comment]
@lcoenen I don't see a comment that this has been pushed for staging. However, they look much better now on staging.

Tables looking much better on mobile view. Approved for both the Birthday Deal and Employees Benefit pages. 👍
