### ISSUE TITLE
[Deals Page] Email not hyperlinked in employees benefit

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#101]
In the Employees Benefit page, the email corporate@whichost.com is not hyperlinked. It's plain text. This is the sentence that you will find it "If providing employees with great benefits is very important for your organisation, contact us at corporate@whichost.com and we will be more than happy to have a chat and provide you with detailed information about our Whichost Employee Benefit."

**Comment by RohrerHope** [comment]
I can't start the contact with companies until this is fixed.

Selling to organisations is not the same as selling to users.

We need to look professional, which means attention to detail.

Thanks 👍

**Comment by buckwierd** [comment]
I'll deal with this issue first thing today ;)

**Comment by buckwierd** [comment]
@lcoenen @RohrerHope done committed and pushed.

**Comment by RohrerHope** [comment]
> @lcoenen @RohrerHope done committed and pushed.

Thanks 👍

**Comment by lcoenen** [comment]
@buckwierd did you pushed to `set-up-deals-pages`?

**Comment by buckwierd** [comment]
Yes. Forgot to mention it ✌️

**Comment by lcoenen** [comment]
Pushed to `staging`

**Comment by RohrerHope** [comment]
The paragraph in which this issue was located has been eliminated properly.

👍
