### ISSUE TITLE
[Deals Page] Email us button in Employees Benefit

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#102]
The email behind the "Email us" button in the Employees Benefit is now the support@whichost.com. In this page that should be corporate@whichost.com.

Also, please make the mailto: so that it includes the subject line "Employees Benefit Enquiry".

Thanks 👍

**Comment by buckwierd** [comment]
@RohrerHope I don't understand your initial description. It's confusing. Which email is the correct one?

**Comment by RohrerHope** [comment]
> @RohrerHope I don't understand your initial description. It's confusing. Which email is the correct one?

The correct one is corporate@whichost.com :) 

Please add a Subject element to the mailto: like "Employees Benefit Enquiry", if possible.

Thanks 👍🏼

**Comment by buckwierd** [comment]
@RohrerHope @lcoenen this was altered and pushed over `set-up-deal-pages`

Note:
The subject line can't be added as per the usual `?subject=abc` link. As this is a `<form action="#" method="get"` request button, I'll have to inform myself what other option we have to add the automated subject line.

As for now, this is to be considered as solved.

**Comment by lcoenen** [comment]
Pushed to staging
