### ISSUE TITLE
[Deals Page] Page title (in the tab) is the same one we had in Staging

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#103]
The page title in the tab of the browser is the same one we had in Staging:

![Annotation 2019-03-19 114715](https://user-images.githubusercontent.com/39112974/54603705-eca15500-4a3c-11e9-90dc-597eb550fc60.jpg)

Please fix this quickly.

**Comment by RohrerHope** [comment]
I can't start the contact with companies until this is fixed.

Selling to organisations is not the same as selling to users.

We need to look professional, which means attention to detail.

Thanks 👍

**Comment by lcoenen** [comment]
@RohrerHope This is fixed. That being said, if you notice an issue on `staging`, please let me know *before* we push to `master`.

**Comment by RohrerHope** [comment]
> @RohrerHope This is fixed. That being said, if you notice an issue on `staging`, please let me know _before_ we push to `master`.

That has been the rule always and I'm very aware of it. :)

However, since there was a rush to push to master, and there were already other issues I reported, I did not want to add more stress to those particular circumstances. :)

I appreciate you understanding on that.

Thanks 👍
