### ISSUE TITLE
[Deals Page] URL for Birthday Deal and Employees Benefit pages

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#104]
For the URL of the birthday deal, please leave it as www.whichost.com/birthday-deal

For the URL of the employees benefit, please leave it as www.whichost.com/employees-benefit

Thanks 👍

**Comment by buckwierd** [comment]
@lcoenen please let me know when this is done. I need to adapt the links in today's social media posts ;)

**Comment by lcoenen** [comment]
Please check the urls at https://whichost-frontend-staging2.herokuapp.com/ that is set on `hotfix-deals-launch-urls`.

Waiting for your thumbup to merge with `master`

**Comment by RohrerHope** [comment]
> Please check the urls at https://whichost-frontend-staging2.herokuapp.com/ that is set on `hotfix-deals-launch-urls`.
> 
> Waiting for your thumbup to merge with `master`

The only one missing is the employees benefit one.

It should be whichost.com/employees-benefit 👍 

Thanks
