### ISSUE TITLE
[Employees Benefit Page] The TH-SU on the table is TU-SU

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#105]
The column for Thursday to Sunday on the table is Tuesday to Sunday.

![Screen Shot 2019-03-19 at 19 27 52](https://user-images.githubusercontent.com/39112974/54635945-3b6edf00-4a7d-11e9-934d-6d00a2ed2d87.jpg)

I believe this is basically changing the U for an H there.

**Comment by lcoenen** [comment]
This have been fixed, please recheck

**Comment by buckwierd** [comment]
I still see TU-SU on the Employee benefit page in staging.
