### ISSUE TITLE
[Employees Benefit page] Delete a paragraph

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#106]
Please delete the paragraph: "If providing employees with great benefits is very important for your organisation, contact us at corporate@whichost.com and we will be more than happy to have a chat and provide you with detailed information about our Whichost Employee Benefit."

Located here:

![Screen Shot 2019-03-22 at 09 00 28](https://user-images.githubusercontent.com/39112974/54811615-059a4800-4c81-11e9-9c1a-b6c0efd452aa.jpg)

I know we have just fixed the corporate@whichost.com hyperlink email issue. However, this page has two times similar paragraphs will call to actions. The main one is the one with the buttons of Email and Call that visitors will find below on the same page.

Thanks 👍

**Comment by buckwierd** [comment]
Fixed. Pushed to `set-up-deal-pages` @lcoenen @RohrerHope

**Comment by lcoenen** [comment]
Pushed to `staging`

**Comment by RohrerHope** [comment]
Approved 👍
