### ISSUE TITLE
[Employees Benefit page] Missing end point to a paragraph

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#107]
The first paragraph after the main title is missing the endpoint after the word salary.

![Screen Shot 2019-03-22 at 09 04 38](https://user-images.githubusercontent.com/39112974/54811858-9c670480-4c81-11e9-9883-689344d53614.jpg)

Thanks 👍🏼

**Comment by buckwierd** [comment]
Fixed. Pushed to `set-up-deal-pages` @lcoenen @RohrerHope

**Comment by lcoenen** [comment]
Pushed to `staging`

**Comment by RohrerHope** [comment]
Approved 👍
