### ISSUE TITLE
[Employees Benefit page] "Employee benefit" must be "Employees Benefit" in the texts.

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#109]
As we discussed with @buckwierd the main words of an element that is significant must be all capitalised. So "Birthday deal" must be "Birthday Deal", and "Employee benefit" should actually be "Employees Benefit".

Now, this one is strange because before the latest push to staging, those texts were fixed. And now they are not:

![Annotation 2019-03-25 082540](https://user-images.githubusercontent.com/39112974/54905025-e2b5a100-4ed7-11e9-842f-37aa0967b97e.jpg)

I don't know what happened there, but I clearly remember seeing on staging that the texts were in the proper format, and "Employee benefit" was "Employees Benefit". Not only on the title of the section and menu item, but also inside the body of the page.

@lcoenen Because I saw that on staging, I considered that that change would be pushed together with the latest push, but it wasn't, and not only that now staging doesn't have those edits.

Especially for the employees benefit page, we need that fixed. It's not "Employee benefit", it's "Employees Benefit".

Please double-check also the body of the page for other areas in which those words need fixing.

I'm marking this as urgent because we can't wait until Friday or next weekend to push this to master since we want to start sending emails to organisations this week. Starting tomorrow.

Thanks 👍

**Comment by buckwierd** [comment]
Employees Benefit was fixed once already and pushed on my side.


Radu S.
Co-Founder / CBO
Founding Team, Whichost Ltd
m: +353-83-452-6597
w: www.whichost.com e: radu@whichost.com


On 25. Mar 2019, 08:33 +0000, Carlos R. <notifications@github.com>, wrote:
> Assigned #109 to @buckwierd.
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
*
*
Please think about the environment before printing this e-mail

This 
email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited. Please also inform us if you or your employer does not accept 
thick kind of e-mail messages.

**Comment by lcoenen** [comment]
https://github.com/Whichost/frontend/blame/master/src/translations/en.json @buckwierd Here is the history of the translations file. On which branch did you pushed the fix?

**Comment by lcoenen** [comment]
This have been fixed on `staging` directly

**Comment by RohrerHope** [comment]
I've reopened this issue because the solution is incomplete.

I confirm that now the capital letters are properly there.

However, Employee Benefit is still in the singular. As you can see from this issue, it has to be "Employees Benefit".

Please, review the menu, title and body of the page so that all "Employee Benefit" becomes "Employees Benefit" (not "Employee Benefits"). This is not a minor detail as we need to say employees in the plural, because these companies have more than one, so we are providing a benefit to all the employees, not just one (employee).

Thanks 👍

**Comment by RohrerHope** [comment]
> I've reopened this issue because the solution is incomplete.
> 
> I confirm that now the capital letters are properly there.
> 
> However, Employee Benefit is still in the singular. As you can see from this issue, it has to be "Employees Benefit".
> 
> Please, review the menu, title and body of the page so that all "Employee Benefit" becomes "Employees Benefit" (not "Employee Benefits"). This is not a minor detail as we need to say employees in the plural, because these companies have more than one, so we are providing a benefit to all the employees, not just one (employee).
> 
> Thanks 👍

@lcoenen I even mention in my comment above "... all "Employee Benefit" becomes "Employees Benefit" (not "Employee Benefits")"

And the change pushed was "Employee Benefits"? :)

![Screen Shot 2019-03-25 at 20 36 28](https://user-images.githubusercontent.com/39112974/54952415-dc5a1000-4f3d-11e9-9f4b-c8351ebfdda1.jpg)


How do I say it so it's clear? This also happened with the URLs.

It's Employees Benefit. Employee must be plural, Benefit must be singular. Employees Benefit.

Thanks 👍
