### ISSUE TITLE
Add a reference to the birthday gift on the front page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#111]
As a visitor falls into our website, www.whichost.com, he will see what we offer, but nowhere we are showing clearly any other benefits, especially our birthday gift.

![what we first see](https://user-images.githubusercontent.com/39112974/55059954-3820b800-5068-11e9-84e9-2e84c721960a.jpg)

Our memory is very fragile, and we forget easily. It's only by repetition that we learn (that's how we learned that 2+2=4 in the early days of our lives, by repetition, by calculating it thousands of times).

To get to the information on our birthday gift, users have to scroll all the way down to our footer, to the bottom of our footer and click on "Deals for you". I believe we can all agree that we are not doing a great job of showcasing our birthday gift.

The purpose of posting this issue is for us to find a proper UX way to showcase our birthday gift to our users, as soon as they fall into www.whichost.com. So they will see it every time they visit us, therefore repetition.

Below is a simple idea to address this (that does not involve complicated coding):

![what we first see - Copy](https://user-images.githubusercontent.com/39112974/55060415-53d88e00-5069-11e9-9cd2-69b74e414984.jpg)

Between the line "Find and book pubs..." and our big CTA "Browse pubs", we put a text line that says:

"Booking for your birthday? We have a gift for you!" Where the phrase "We have a gift for you!" is hyperlinked to the birthday deal page.

😄 👍

**Comment by buckwierd** [comment]
We’ll do that and we will also have to put it somewhere else too on the main page. I suggest two big pictures next to each other. One about the Birthday Deal and one about the Employees Benefit. 

Let’s talk about it on Friday 😉

**Comment by RohrerHope** [comment]
Added to be pushed to master this week.

Let's push the text improvement and afterwards, we can work on the section inside the main page with one image per benefit to promote them.

Thanks 👍

**Comment by lcoenen** [comment]
@buckwierd Could you style those two lines? They are in `src/components/SectionHero/SectionHero.js`

         <h2 className={css.temporaryOffer}>
          <FormattedMessage id="SectionHero.temporaryOffer" /> 
					<NamedLink 
						name="BirthdayDealPage"
						className={css.temporaryOfferLink}	
					>
						<FormattedMessage id="SectionHero.temporaryOfferLink" /> 
					</NamedLink>
        </h2>

In the corresponding CSS, you'll see classes `.temporaryOffer` and `.temporaryOfferLink`, I cannot find a way to make it look like the picture.

**Comment by buckwierd** [comment]
Started.

**Comment by buckwierd** [comment]
Done. Pull request will follow.

<img width="917" alt="Screenshot 2019-04-01 at 14 06 34" src="https://user-images.githubusercontent.com/45966402/55329857-8af2d900-5487-11e9-9fb6-17bd158d639a.png">

**Comment by buckwierd** [comment]
@lcoenen I've created a pull request for this but I'm not sure you received it. Creating a pull request looks pretty confusing for me. Inc ase the pull request went wrong, I've pushed the change over `set-up-deal-pages`.

**Comment by RohrerHope** [comment]
Approved in staging 👍🏼

**Comment by RohrerHope** [comment]
Approved in staging 👍
