### ISSUE TITLE
Addressing how much the employees benefit cost

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#112]
As with anything that is offered to us, we will immediately think where's the cost, and how much will it cost us to get it.

In our Employees Benefit page, we are not addressing that question of cost.

So here is my idea to address that:

![at no cost](https://user-images.githubusercontent.com/39112974/55061492-cd717b80-506b-11e9-92b0-55c2ba0055f2.jpg)

We take this line:

"Give your employees the benefit of enjoying an Amazon Gift Card of up to € 300.00 on us, with every party they book through Whichost!"

And we convert it to this:

"**Give your employees the benefit of enjoying an Amazon Gift Card of up to € 300.00 on us, with every party that they book through Whichost, at no cost to your organisation!**"

Yes, bold text included in the entire phrase, so that it's highlighted. Also please note that I added a "that" between "party" and "they".

Thanks 👍

**Comment by buckwierd** [comment]
Great! Will deal with it today

**Comment by RohrerHope** [comment]
> Great! Will deal with it today

Thanks.

**Comment by RohrerHope** [comment]
Added to be pushed to master this week.

Thanks 👍

**Comment by lcoenen** [comment]
@RohrerHope So is this done?

**Comment by RohrerHope** [comment]
I see it okay in staging.

**Comment by buckwierd** [comment]
@lcoenen what's the status with this one? If it can be pushed to master, please do so.

**Comment by lcoenen** [comment]
@buckwierd the point of `staging` is that we merge everything at the same time.

**Comment by RohrerHope** [comment]
Approved in staging 👍🏼

**Comment by RohrerHope** [comment]
Approved in staging 👍
