### ISSUE TITLE
Add time field in booking process

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#127]

**Comment by lcoenen** [comment]
This have been done in `add-time-field-in-booking-process`. Styling is way from being perfect but the information is stored and showed correctly.

**Comment by buckwierd** [comment]
Can't work on this. Here's the error message on localhost after copmpiling:

Error: clientId must be provided
▼ 3 stack frames were expanded.
wt
node_modules/sharetribe-flex-sdk/build/sharetribe-flex-sdk-web.js:1
new t
node_modules/sharetribe-flex-sdk/build/sharetribe-flex-sdk-web.js:1
h
node_modules/sharetribe-flex-sdk/build/sharetribe-flex-sdk-web.js:1
▲ 3 stack frames were expanded.
./src/index.js
src/index.js:86
  83 | // eslint-disable-next-line no-underscore-dangle
  84 | const preloadedState = window.__PRELOADED_STATE__ || '{}';
  85 | const initialState = JSON.parse(preloadedState, sdkTypes.reviver);
> 86 | const sdk = createInstance({
  87 |   transitVerbose: config.sdk.transitVerbose,
  88 |   clientId: config.sdk.clientId,
  89 |   secure: config.usingSSL,
View compiled
▼ 6 stack frames were expanded.
__webpack_require__
/Users/sighencea/Documents/GitHub/Whichost/frontend/webpack/bootstrap 22994b02b7b104e114ab:678
fn
/Users/sighencea/Documents/GitHub/Whichost/frontend/webpack/bootstrap 22994b02b7b104e114ab:88
0
http://localhost:3000/static/js/bundle.js:236094:18
__webpack_require__
/Users/sighencea/Documents/GitHub/Whichost/frontend/webpack/bootstrap 22994b02b7b104e114ab:678
(anonymous function)
/Users/sighencea/Documents/GitHub/Whichost/frontend/webpack/bootstrap 22994b02b7b104e114ab:724
(anonymous function)
http://localhost:3000/static/js/bundle.js:728:10
▲ 6 stack frames were expanded.

**Comment by buckwierd** [comment]
@lcoenen please advise what I need to do.

**Comment by lcoenen** [comment]
@buckwierd same as the other one, add the correct `.env` file. What's surprising is that it's not supposed to be erased everytime you switch to a new branch. 

Are you sure you're not staging the `.env` file?

**Comment by lcoenen** [comment]
I am working on it. 

**Work on it**:

- Place the card in `ongoing` column
- Tag it with `ongoing`

**Comment by lcoenen** [comment]
**What have been done**: The booking process have been updated. We add a time field. We tidied styling up. 
**Pushed to**: `add-time-field-in-booking-process`
**Tag somebody**: @buckwierd 
**PR**: #134

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by buckwierd** [comment]
Can't test it at the moment. 
Issue:
After selecting a date and clicking on "Request to book" I get the message "The listing author has not added their payment information and the listing cannot be booked at the moment."

Anyone knows a L on staging that has a valid payout method saved?
@lcoenen @RohrerHope

**Comment by lcoenen** [comment]
@buckwierd you can test on the Cotton Ball

**Comment by buckwierd** [comment]
@lcoenen don't see any time field on staging.

**Comment by lcoenen** [comment]
@buckwierd it's not on staging, it's on `add-time-field-in-booking-process`

**Comment by buckwierd** [comment]
@lcoenen if I have to test it through Heroku, please explain the steps. I have no clue hot that works.

**Comment by lcoenen** [comment]
@buckwierd you just checkout the branch and check locally. You do that all the time :)

**Comment by buckwierd** [comment]
This poor explanation doesn’t tell me anything. Without a step by step instruction I can’t move forward with this. I will also stop discussing around the subject.

**Comment by lcoenen** [comment]
Ok, well this will stay staged then.

**Comment by RohrerHope** [comment]
![Screen Shot 2019-04-24 at 20 21 35](https://user-images.githubusercontent.com/39112974/56687596-9aec8a00-66ce-11e9-9295-41c319b8ecc3.jpg)

Instead of "You can only throw a party before 12PM."

It should say "You can only throw a party after 12PM."

The validation is working, but the wording is incorrect.

Thanks 👍

**Comment by lcoenen** [comment]
I am working on it. 

**Work on it**:

- Place the card in `ongoing` column
- Tag it with `ongoing`

**Comment by lcoenen** [comment]
**What have been done**: Replaced the typo (before -> after)
**Pushed to**: `add-time-field-in-booking-process`.
**Tag somebody**: NA

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by buckwierd** [comment]
The issue has been implemented/fixed correctly.
