### ISSUE TITLE
Add a help link on the mobile login screen

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#139]
Here is the link that we needed to adjust

![image](https://user-images.githubusercontent.com/1237971/56059946-59b6ba80-5d5d-11e9-97cf-78a38e370090.png)

**Comment by lcoenen** [comment]
This have been fixed on `staging`

**Comment by RohrerHope** [comment]
When logged in:

![help inside menu when logged in](https://user-images.githubusercontent.com/39112974/56294364-cd244780-6122-11e9-8419-9c6a58a1a6d1.jpg)

When not logged in:

![help inside menu when logged out](https://user-images.githubusercontent.com/39112974/56294378-d2819200-6122-11e9-81e3-90e526f56420.jpg)

Looks good to me.

Thanks.
