### ISSUE TITLE
Change the font of booking agenda

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#142]
**What's to be corrected** font of the agenda when booking
![image](https://user-images.githubusercontent.com/1237971/56298681-7c185180-612a-11e9-8670-03b6448a804c.png)
**How should it look like (screenshot or sketch)**: 
![image](https://user-images.githubusercontent.com/1237971/56298728-94886c00-612a-11e9-820a-bcbd208aa956.png)

**How should it work (write use case)**: no change

**Priority (tag accordingly):** `non-urgent`
**Domain (tag accordingly):** `frontend`
**Tested on:** Mac OS Mojave 10.14.3 Chrome 73
**Branch**: `staging)

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@buckwierd is the font used correctly here? It uses Lato, but it's a Seriff font, it shouldn't be used here imo.

**Comment by buckwierd** [comment]
On my end the loaded font is Lato and everything looks fine.

**Comment by lcoenen** [comment]
@scottyzen Thanks, this is fixed!

For the sake of organization, it would be cool to use the [saved replies ](https://github.com/Whichost/frontend/wiki/Saved-replies). Those will tell you what to do so we're all on the same page. For example, please create a PR in this kind of case, because sometime we just lose track on the branch we work on and things get delayed :)

But thanks anyway!
