### ISSUE TITLE
Replace "price per night" in booking breakdown

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#144]
**What's to be corrected**: The "price per night" label in booking breakdown
![image](https://user-images.githubusercontent.com/1237971/56300226-73754a80-612d-11e9-80c8-25f81d7eba12.png)
**How should it look like (screenshot or sketch)**:

![image](https://user-images.githubusercontent.com/1237971/56300321-a6b7d980-612d-11e9-960d-ce7ff906c7c1.png)

**How should it work (write use case)**: The breakdown should be adapted to our use case (booking parties). 

**Priority (tag accordingly):** `regular`
**Domain (tag accordingly):** `frontend`
**Branch**: `staging`

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
**What have been done**: We changed the translations to indicate "Per booking" instead of "Per night". 
**Pushed to**: `staging`.
**Tag somebody**: @buckwierd 
**PR**: NA, test on staging (https://whichost-frontend-staging.herokuapp.com/l/the-cotton-ball-cork/5c0a5516-6f5b-45b1-bfb6-22b157f77d8a).

![image](https://user-images.githubusercontent.com/1237971/57182799-a3497f80-6e9b-11e9-8201-c62f6655c9b3.png)


**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by buckwierd** [comment]
The issue has been implemented/fixed correctly.
