### ISSUE TITLE
Remove the end date in host inbox

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#145]
**What's to be corrected**: The host inbox is still showing the end date. That could be confusing for the host.
![image](https://user-images.githubusercontent.com/1237971/56306238-e2f13700-6139-11e9-94f0-103a5f309b52.png)
**How should it look like (screenshot or sketch)**:
![image](https://user-images.githubusercontent.com/1237971/56306316-09af6d80-613a-11e9-8301-26a94bd3bec9.png)

**Priority (tag accordingly):** `regular`
**Domain (tag accordingly):** `frontend`
**Tested on:** Mac OS Mojave 13.1.4 Chrome 73
**Branch**: `staging`. 

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

**Validate**

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
**What have been done**: We removed the end date from the host inbox
**Pushed to**: `remove-the-end-date-in-host-inbox`
**Tag somebody**: @buckwierd 
**PR**: N/A, please test on https://whichost-frontend-staging.herokuapp.com/inbox/sales

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by buckwierd** [comment]
@lcoenen can't test it. The link brings me to my profile's hosting page but I don't have any bookings to test. I'll test this later with Aoife's profile, because she has a booking with Treasa on master. Can you push this to master so we can test it there directly?
