### ISSUE TITLE
Create a career page

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#150]
**What's the improvement**: We need to create a `career` page to get rid of squarespace.
**How should it look like (screenshot or sketch)**: The actual implementation will be done by @buckwierd 

**How should it work (write use case)**: It should replace the `career` link in the footer

**Priority (tag accordingly):** `urgent`
**Domain (tag accordingly):** `frontend`
**Branch**: `create-career-page` derived from `create-static-pages`

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

**Validate**

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@buckwierd This have been created and pushed to `create-career-page`

**Comment by buckwierd** [comment]
@lcoenen thanks. I'm on it now.

**Comment by buckwierd** [comment]
Done. Pull request will follow.

**Comment by lcoenen** [comment]
@buckwierd Thanks :) Please use the following template: 

```
**What have been done**: 
**Pushed to**: (branch)
**Tag somebody**: 
**PR**: (create a PR if the branch is ready to be merged)

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.
```

You can save answers by clicking here:

![image](https://user-images.githubusercontent.com/1237971/56516889-858f2880-6533-11e9-81b5-d53e84bdf39f.png)

**Comment by RohrerHope** [comment]
I don't see the career page anywhere inside staging.

I see we are hiring, but it takes me to Squarespace.

**Comment by lcoenen** [comment]
@RohrerHope The same goes here. The "We're hiring" link now points to the Career Page.
