### ISSUE TITLE
Change "Amazon Gift Card" to "One4all Gift Card" in all deals and benefits pages

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#153]
**What's to be corrected**: All texts in the deals pages (Birthday and Corporate) where it says "Amazon Gift Card" needs to be changed for "One4all Gift Card".
**How should it look like (screenshot or sketch)**: Instead of saying "Amazon Gift Card" it will say "One4all Gift Card".
**How should it work (write use case)**: N/A

**Priority (tag accordingly):** `urgent` / `regular` (`next` column) or `non-urgent` / `wontfix` (`backlog` column)
**Domain (tag accordingly):** `frontend` / `backend`
**Tested on:** (platform, OS, browser, version)
**Branch**: (commit directly to `staging` / PR to `master` if it's `urgent`)

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by RohrerHope** [comment]
Just want to reinforce that this is urgent. 😉 

I can't continue to send emails with "Amazon Gift Card" up there. 👍 

Also, Abtran likes this and they are evaluating it.

Thanks.

**Comment by buckwierd** [comment]
@RohrerHope this will be done on my side in approximately 15 minutes.

**Comment by RohrerHope** [comment]
> @RohrerHope this will be done on my side in approximately 15 minutes.

Thanks. Please make sure you search for all sections in which "Amazon Gift Card" could be in it. In the intro page, T&Cs, Examples for the Corporate Deal.

Same thing for the Birthday Deal. Please check every section.

All "Amazon Gift Card" messages and references need to be changed to "One4all Gift Card".

Thanks 👍

**Comment by buckwierd** [comment]
Done. Used the branch `set-up-deal-pages`. Pull request will follow.

**Comment by RohrerHope** [comment]
Hi guys. Where can I test this?

**Comment by RohrerHope** [comment]
![Screen Shot 2019-04-24 at 20 04 03](https://user-images.githubusercontent.com/39112974/56686687-72639080-66cc-11e9-8abf-98dca7e54c28.jpg)

Points 6 and 6.1 existed because of the Amazon Gift Cards. With One4all cards, those points are not necessary and we have to remove them. Especially because they make reference to Amazon.

Thanks. 👍

**Comment by lcoenen** [comment]
I am working on it. 

**Work on it**:

- Place the card in `ongoing` column
- Tag it with `ongoing`

**Comment by RohrerHope** [comment]
Hi @lcoenen 

I marked this issue as urgent but it seems that is not what triggers an issue to be taken care off immediately and push to master.

What is the procedure in order to report an issue that needs to be pushed to master with urgency (like the same day)?

That was my intention with this one, and that's why I marked it as urgent.

Thanks 👍

**Comment by lcoenen** [comment]
You followed the procedure all right, but the PR have been created to `staging` instead of master. 

We will talk about that tomorrow.

**Comment by lcoenen** [comment]
This will be pushed through staging since the PR have been incorrectly created.
The issue is fixed.

**Comment by RohrerHope** [comment]
I checked again and it looks good to me.
