### ISSUE TITLE
Improve the Birthday and Corporate Deal pages

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#157]
**What's the improvement**:

1. Improve the Birthday Gift page design to simplify it and make it cleaner.
1. Change "Birthday Deal" to "Birthday Gift" all around the page and menu
1. Change all references to "Deals" to "Benefits".

**How should it look like (screenshot or sketch)**:

![Birthday Gift Proposal Page 001](https://user-images.githubusercontent.com/39112974/56847411-4dd90580-68d2-11e9-9676-307227481dba.jpeg)

**How should it work (write use case)**: N/A. Improvement of design.

**Priority (tag accordingly):** `urgent` / `regular` (`next` column) or `non-urgent` / `wontfix` (`backlog` column)
**Domain (tag accordingly):** `frontend` / `backend`
**Tested on:** (platform, OS, browser, version)
**Branch**: `improve-the-birthday-and-corporate-deal-pages`.

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by buckwierd** [comment]
Works ongoing. Here's how the coded page looks now. Waiting for #161 and #158 to be finalized, before I can finish this page.
<img width="909" alt="Screenshot 2019-04-27 at 19 11 41" src="https://user-images.githubusercontent.com/45966402/56853461-52c4a600-6920-11e9-8d89-7b1047520aa8.png">

**Comment by RohrerHope** [comment]
> Works ongoing. Here's how the coded page looks now. Waiting for #161 and #158 to be finalized, before I can finish this page.
> <img alt="Screenshot 2019-04-27 at 19 11 41" width="909" src="https://user-images.githubusercontent.com/45966402/56853461-52c4a600-6920-11e9-8d89-7b1047520aa8.png">

Looking good @buckwierd 

Same comment about the T&Cs text here, that I made on the other issue on the Corporate Benefit.

Thanks 👍

**Comment by RohrerHope** [comment]
@buckwierd 

Very important.

We are changing the expression we use for the Birthday Deal to Birthday Gift, and Employees Benefit to Corporate Benefit. 

Not only this needs to change in the Birthday Gift page, but it also must change anywhere else inside the platform where we mention the Birthday Gift (where we are still using Birthday Deal).

The same thing applies to the Corporate Benefit. There may be other sections inside the platform where we talk about Employees Benefit. These must also change to Corporate Benefit.

Thank you 👍

**Comment by buckwierd** [comment]
Done. PR will follow.

**Comment by RohrerHope** [comment]
**What's wrong**: 

The sentence "Get up to €240 when celebrating your birthday." is off. It needs to be orange, and centred. Much like what happens in the "Corporate Benefit" page and the "Recommend Reward" one.

![Screen Shot 2019-05-03 at 06 58 12](https://user-images.githubusercontent.com/39112974/57121709-20c4a100-6d71-11e9-888d-fe940cb133f8.jpg)

- **Also**, the links for the T&Cs in each of these pages are taking me to 404 and they are opening in new tabs, and not on the same page. Please review that all links are working in them (Birthday, Recommend and Corporate page).

**How it should be**: 

As an example, the Corporate Benefit page:

![Screen Shot 2019-05-03 at 07 01 46](https://user-images.githubusercontent.com/39112974/57121750-55385d00-6d71-11e9-8fad-5b868d56198c.jpg)

I moved the corresponding card to `Still have issues` column on the board and I reopen the issue.

**Comment by lcoenen** [comment]
@buckwierd, in `src/components/BirthdayDeal/BirthdayDeal.js`, you coded the link like that:

    		<div className={css.readMore}>
		<a href="https://www.whichost.com/legal/benefits" target="_blank">Birthday Gift Terms &amp; Conditions</a>
		</div>

Here's a few remarks:

1. Please use correct indentation. It will make re-reading easier.
2. Please use `<NamedLink>` instead of `<a>`. `<NamedLink>` allow us to change the URL of a page without having to re-write it everywhere. It is used like that: 

    <NamedLink name="NameOfThePage">Text of the link</NamedLink>

You can find the name of the page in `src/route-configuration.js`

3. Please use `target="_blank"` with parsimony.

**Comment by lcoenen** [comment]
**What have been done**: We fixed the link in Corporate Deal and Birthday Deal
**Pushed to**: `improve-the-birthday-and-corporate-deal`
**Tag somebody**: @RohrerHope 
**PR**: https://whichost-frontend-stagi-pr-184.herokuapp.com/

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by RohrerHope** [comment]
@lcoenen 

If possible, please update the top phrase in the Birthday Gift page to "Earn a gift card to use with over 2,000 shops in Ireland & the UK!"

If possible, please update the top phrase in the Corporate Benefit page to "Give your employees a gift card to use with over 2,000 shops in Ireland & the UK!"

Why? Because in our T&C we indicate that the benefit is for both countries and because One4all work also in the UK.

If not possible, then I'll create a new hot fix issue after this push to master.

Thanks.

**Comment by lcoenen** [comment]
@RohrerHope The issue is already closed. Please create a new issue,

**Comment by RohrerHope** [comment]
Okay, thanks.
