### ISSUE TITLE
Add Benefits terms in a Legal page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#160]
**What's the improvement**: 

1. Add to the T&Cs page the ones for the "Birthday Gift", "Recommend Gift" and "Corporate Benefit".
1. Add them below our regular T&Cs, with no need to create independent menu items for each of them.

**How should it look like (screenshot or sketch)**:

1. These T&Cs are added at the end of our regular T&Cs in this order: Birthday Gift, Recommend Gift and Corporate Benefit.
1. In their respective pages there will be links to these T&Cs, so we need to make sure that when users click on those links it will take them directly to the position of the corresponding T&Cs. Example: if they click on "Birthday Gift Terms and Conditions" it will take them directly to the section, inside the T&Cs, that refers to the "Birthday Gift" T&Cs.

**How should it work (write use case)**: N/A. It's just adding more text to the T&Cs.

**Priority (tag accordingly):** `regular` (`next` column)
**Domain (tag accordingly):** `frontend`

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by buckwierd** [comment]
@RohrerHope I'm confused. Yesterday we also said we add on the legal page a new side menu item called "Benefits". This new item will contain the T&C for the Benefits.

Please let me know how you would like to proceed before I start working on it:
1. Add the benefits as you described at the bottom of the current T&C page
2. Add on the legal page a new side menu item called "Benefits". This new item will contain only the T&C for the Benefits

I would like to move forward with no.1 as it is easier and faster to implement.

@lcoenen which branch would be the right one in this case?

**Comment by RohrerHope** [comment]
> @RohrerHope I'm confused. Yesterday we also said we add on the legal page a new side menu item called "Benefits". This new item will contain the T&C for the Benefits.
> 
> Please let me know how you would like to proceed before I start working on it:
> 
> 1. Add the benefits as you described at the bottom of the current T&C page
> 2. Add on the legal page a new side menu item called "Benefits". This new item will contain only the T&C for the Benefits
> 
> I would like to move forward with no.1 as it is easier and faster to implement.
> 
> @lcoenen which branch would be the right one in this case?

@buckwierd 

Sorry, I missed that.

Let's go with the option we discussed of creating the new side menu called "Benefits" and put the benefits T&Cs in there.

Thanks 👍

**Comment by lcoenen** [comment]
@buckwierd since this is an improvement (a new feature), we will have to create a new branch that derive from `staging`. For that, you can wait for me to create the branch or create it yourself from `staging`. I will create it this time, but for future reference, here is the process:

1. Navigate to the code in github.com

![image](https://user-images.githubusercontent.com/1237971/56852464-b5fc0b80-6913-11e9-8194-4f3641ec7db9.png)

2. Select the `staging` branch:

![image](https://user-images.githubusercontent.com/1237971/56852472-ca400880-6913-11e9-8fa0-eeee1fc10823.png)

3. Once you selected (checked out) the staging branch, type the name of the new branch in the `find or create a branch` field: 

![image](https://user-images.githubusercontent.com/1237971/56852478-ee9be500-6913-11e9-91b3-20364766b0d6.png)

4. In this case, use the title of the issue, in small caps and hyphenated (so `add-benefits-terms-in-legal-page`).

5. After that, the branch should appear on Github desktop.

**Comment by RohrerHope** [comment]
@buckwierd 

I've drafted a T&Cs for the Recommend Gift benefit here: https://docs.google.com/document/d/10QJIkSMLU4r8v7wvVFh0uDZcrAquUya4DgVCsKmgRMY/edit#

Thanks.

**Comment by lcoenen** [comment]
**What have been done**: I created a new page in `legals`
**Pushed to**: `add-benefits-terms-in-a-legal-page`
**Tag somebody**: @buckwierd

**Comment by lcoenen** [comment]
**Erratum** - @buckwierd the branch isn't on the server. I will need to get back to you on this. Sorry about the delay.

**Comment by lcoenen** [comment]
All yours, @buckwierd, sorry about that.

**Comment by buckwierd** [comment]
Done. PR will follow.

**Comment by RohrerHope** [comment]
@lcoenen @buckwierd 

I can't find where this page is to test it.

Supposedly this page should be together on the same page where T&Cs are, but I don't see it there.

Am I missing something?

Thanks.

**Comment by lcoenen** [comment]
@RohrerHope the page is on staging... 

https://whichost-frontend-staging.herokuapp.com/legal/benefits

**Comment by buckwierd** [comment]
The issue has been implemented/fixed correctly.

**Comment by RohrerHope** [comment]
In both the Benefit Gift and the Corporate Benefit T&Cs we had already deleted points 3.3 and 3.3.1.

![Screen Shot 2019-05-06 at 08 27 46](https://user-images.githubusercontent.com/39112974/57211667-07259280-6fd9-11e9-855e-479c19548717.jpg)

Please delete them before pushing to master.
