### ISSUE TITLE
Create "Benefits" side menu item on legal page

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#161]
**What's the improvement**: Adding the Benefits T&C to the legal page

**How should it look like (screenshot or sketch)**: Add a new side menu item on the legal page called "Benefits", underneath "Terms of Service".

**How should it work (write use case)**: See #160 

**Priority (tag accordingly):** `regular`

**Domain (tag accordingly):** `frontend`

**Tested on:** N/A

**Branch**: @lcoenen please tell me which branch I need to use, because it will be the same for #160

**Comment by lcoenen** [comment]
@buckwierd this is the same feature as #160 and should not be in a different issue. 

Closing as duplicate.
