### ISSUE TITLE
Fix links in FAQ

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#168]
**What's to be fixed**:

Another link in the FAQ that it takes people to the top of the FAQ page and not to where it should take them.

![Screen Shot 2019-04-28 at 12 34 20](https://user-images.githubusercontent.com/39112974/56863747-2194b600-69b2-11e9-8608-b4f171af64cf.jpg)

Report a no-show should take them to report a no-show, and not to the top of the FAQ page.

**This issue is for all links inside the FAQ to be reviewed**, so I don't create one issue per link, because so far I tested 2, and the 2 failed.

**What's the expected behavior:**

Take them to where the link is indicating it will take them, and not to the top of the FAQ page!

**What happens in reality (screenshot):**

![Screen Shot 2019-04-28 at 12 32 55](https://user-images.githubusercontent.com/39112974/56863759-3d985780-69b2-11e9-99f6-bbe2b2197df8.jpg)

**Priority (tag accordingly):** `urgent`
**Domain (tag accordingly):** `frontend`
**Tested on:** _(please fill)_
**Branch**: `hotfix-fix-links-in-FAQ` (derived from `master`)

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope Don't forget to add the Project to the issues so we can keep track of them :)

![image](https://user-images.githubusercontent.com/1237971/56864628-bdc3ba80-69bc-11e9-8e78-75753dc6fdd1.png)

**Comment by RohrerHope** [comment]
> @RohrerHope Don't forget to add the Project to the issues so we can keep track of them :)
> 
> ![image](https://user-images.githubusercontent.com/1237971/56864628-bdc3ba80-69bc-11e9-8e78-75753dc6fdd1.png)

Will do.

Thanks.

**Comment by lcoenen** [comment]
@RohrerHope The forms were on sharetribe, we need to wait for issue #136 to be fixed before we can handle that properly. 

In the meanwhile, this link will just redirect to the Contact Us form.

**Comment by RohrerHope** [comment]
> @RohrerHope The forms were on sharetribe, we need to wait for issue #136 to be fixed before we can handle that properly.
> 
> In the meanwhile, this link will just redirect to the Contact Us form.

No-Show is a Google Form: https://docs.google.com/forms/d/1jZ1aH21YDcqelSC3F7628ZWxvOZR2QPacA5lRV8O70c/edit

If that's what your comment is related to.

Inside Squarespace, we only had the claim form, which is now being moved to the contact form.

The No-show is that Google Form.

Let me know if you have questions about any of the other links. 

Thanks 👍

**Comment by lcoenen** [comment]
**What have been done**: We fixed the links in the FAQPage - including the Google forms links
**Pushed to**: `hotfix-fix-links-in-FAQ`
**Tag somebody**: @RohrerHope 
**PR**: #172 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.
