### ISSUE TITLE
Fix pricing inside Pub Fees

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#169]
**What's to be fixed**:
I reported this in another issue. The pricing for pubs is incorrect.

![Screen Shot 2019-04-28 at 12 39 46](https://user-images.githubusercontent.com/39112974/56863799-bdbebd00-69b2-11e9-992b-b9647170ebf0.jpg)

**What's the expected behavior:**

Please review here for the actual pricing: https://docs.google.com/spreadsheets/d/1vYB1vH87QR-89XWQjPYQwRQFgGR0hG8LPIpZ-CoVjDo/edit#gid=0

![Screen Shot 2019-04-28 at 12 40 56](https://user-images.githubusercontent.com/39112974/56863813-e47cf380-69b2-11e9-9279-305c24a5a605.jpg)

**What happens in reality (screenshot):**

![Screen Shot 2019-04-28 at 12 39 46](https://user-images.githubusercontent.com/39112974/56863815-eba40180-69b2-11e9-9d15-e50284fd009a.jpg)

**Priority (tag accordingly):** `urgent`
**Domain (tag accordingly):** `frontend` / `backend`
**Branch**: `hotfix-fix-pricing-inside-pub-fees` (derived from `master`)

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

**Validate**

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by buckwierd** [comment]
@RohrerHope which tab of the fees file is the one I need to implement? Is it `Business Model (Customers and Providers)`

**Comment by RohrerHope** [comment]
> @RohrerHope which tab of the fees file is the one I need to implement? Is it `Business Model (Customers and Providers)`

The first tab: Business Model (Customers and Providers)

Rows 4 - 12 as per the screenshot in my previous comment 👍 

![Screen Shot 2019-04-28 at 12 40 56](https://user-images.githubusercontent.com/39112974/56866778-5a925200-69d5-11e9-843f-a7f09d397638.jpg)

Thanks.

**Comment by buckwierd** [comment]
Done. PR will follow.

**Comment by lcoenen** [comment]
@buckwierd please close the issue and move the card accordingly.
