### ISSUE TITLE
Improve landing page main button CTA text

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#182]
**What's to be corrected**: 

Our current main button CTA in our landing page says "Browse pubs".

Browsing is not an actual friendly and clear invitation to find the pub that you want for your party, as browsing means you are scrolling through information. That's why other platforms don't use that expression "Browse".

Airbnb, Booking, Google and many others use the expression "Search". However, Search in all those cases are linked previously to the visitor entering information, what they want to find, and then clicking on Search.

In our case, we don't have that yet in that button section.

So my proposal is we improve the text in that button to "Get started", instead of "Browse pubs". Get started is a more friendly invitation that connects better with our value proposal "Find and book pubs for your parties and celebrations" --> "Get started" (on finding it)

This is our current landing page CTA button:

![landing page big button original](https://user-images.githubusercontent.com/39112974/57010653-b5a28f80-6bf5-11e9-918a-c0dfa12a6337.jpg)

**How should it look like (screenshot or sketch)**:

The proposal has two parts:

1. "Browse pubs" changes to "Get started"
1. Font weight changes from "600" to "normal".

![landing page big button get started](https://user-images.githubusercontent.com/39112974/57010672-d36ff480-6bf5-11e9-8961-23b8f3134b26.jpg)

**How should it work (write use case)**:

N/A. This is a text improvement.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version): Dell, Windows 10, Chrome, the latest version
**Branch**: Staging

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by RohrerHope** [comment]
As we discussed yesterday, the text in the button can be "Find a pub".

This is a trivial change. 

@lcoenen  Can we also include this change in this coming push to master?

Thanks.

**Comment by lcoenen** [comment]
@RohrerHope yes I can. Just a remark: an issue is either a feature, a bug or a trivial change. The flow is different for each, thus, please don't use two of those labels for the same issue.

**Comment by lcoenen** [comment]
**What have been done**: We changed the label to "Find a pub"
![Uploading image.png…](Find a pub button)
**Pushed to**: `staging`
**Tag somebody**: @RohrerHope 
**Where to test**: https://whichost-frontend-staging.herokuapp.com/

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by buckwierd** [comment]
The issue has been implemented/fixed correctly.

**Comment by RohrerHope** [comment]
The issue has been correctly implemented/fixed.
