### ISSUE TITLE
Include the UK in the Deals page's top phrase.

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#190]
**What's to be corrected**: 

- In the Birthday Gift page, it says: Earn a gift card to use with over 2,000 shops in Ireland!
- In the Recommend Reward page, it says: Earn a gift card to use with over 2,000 shops in Ireland!
- In the Corporate Benefit page, it says: Give your employees a gift card to use with over 2,000 shops in Ireland!

None of them includes the UK. However, the UK is part of our benefit, it's included in our T&Cs and One4all cards also operate in the UK.

**How should it look like (screenshot or sketch)**:

- In the Birthday Gift page, it should say: Earn a gift card to use with over 2,000 shops in Ireland & the UK!
- In the Recommend Reward page, it should say: Earn a gift card to use with over 2,000 shops in Ireland & the UK!
- In the Corporate Benefit page, it should say: Give your employees a gift card to use with over 2,000 shops in Ireland & the UK!

This must be applied both for mobile and desktop views.

**Please, always notice capitalisations and other grammatical elements in sentences. They are there for a reason.**

**How should it work (write use case)**:

N/A. This is a text improvement.

**Priority (tag accordingly):** Urgent
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version): Mac, Mac OS latest, Chrome, Chrome latest
**Branch**: PR to master

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
**What have been done**: Include the UK in the Benefits page's top phrase
**Pushed to**: `staging`
**Tag somebody**: @RohrerHope 
**Where to test**: https://whichost-frontend-staging.herokuapp.com/benefits/recommend-gift

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by lcoenen** [comment]
@RohrerHope Don't forget that we are still using the Deals terminology for internal purposes.

**Comment by RohrerHope** [comment]
**What's wrong**: 

The first two phrases on each of the Benefits pages are independent and run in their own lines. They were in two different lines before, and now they are in one for the Birthday Gift and the Recommend Reward.

This is the Birthday Gift page:

![Screen Shot 2019-05-06 at 13 15 14](https://user-images.githubusercontent.com/39112974/57224390-3b14ae00-7001-11e9-961e-87dd21acdc8a.jpg)

This is the Recommend Reward page:

![Screen Shot 2019-05-06 at 13 15 07](https://user-images.githubusercontent.com/39112974/57224406-47007000-7001-11e9-8249-3fa53abb3aef.jpg)

This is the Corporate Benefit page (which is correct in its design, **one phrase per line**):

![Screen Shot 2019-05-06 at 13 15 00](https://user-images.githubusercontent.com/39112974/57224427-567fb900-7001-11e9-9f29-02b34112a6b8.jpg)

**How it should be**: 

In the Birthday Gift page, this line "Earn a gift card to use with over 2,000 shops in Ireland & the UK!" is in an independent line from "Get up to €240 when celebrating your birthday." and they are both centred.

In the Recommend Reward page, this line "Earn a gift card to use with over 2,000 shops in Ireland & the UK!" is in an independent line from "Get €15 for recommending a pub and celebrating there." and they are both centred.

You can use the Corporate Benefit page as a reference.

These pages were okay in their designs before this issue. I don't know why the design changed.

Thanks.

I moved the corresponding card to `Still have issues` column on the board and I reopen the issue.
