### ISSUE TITLE
Improve the birthday message in landing page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#195]
**What's to be corrected**: 

This is our current birthday message on the landing page:

![current message](https://user-images.githubusercontent.com/39112974/58035547-ee60c500-7b20-11e9-9c9c-4e8c50685690.jpg)

"Booking for your birthday? We have a gift for you!"

**How should it look like (screenshot or sketch)**:

This is proposed change to improve it in two ways: 1- It says what the gift is, a gift card and 2- it says how much you can receive.

![proposed birthday message](https://user-images.githubusercontent.com/39112974/58035622-151efb80-7b21-11e9-9ac2-a9b60389f220.jpg)

"Booking for your birthday? Get a gift card of up to €240!"

**How should it work (write use case)**:

N/A. This is a text improvement.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version): Windows, 10, Chrome, latest
**Branch**: Staging

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
The issue have been correctly implemented / fixed. PR number *Reference PR here have been merged.
