### ISSUE TITLE
Improve benefits page in help centre

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#202]
**What's to be corrected**: 

Title
From "Part of our culture is giving back"
To "Giving back is in our culture"

Line
From "At Whichost we spent days and nights contemplating about how we can further benefit the community. We turn general ideas into presentations and finally into actions."
To "At Whichost we spent days and nights contemplating how we can further benefit the community. We turn ideas into presentations and finally into actions."

Line
From "At the moment we have three active benefits for our members. Both are linked to attractive rewards and you can read more on the following benefits pages."
To "At the moment we have three active benefits. All linked to attractive rewards and you can read more on the following pages."

Line
From "Browse pubs and book now!"
To "Find a pub and book it now!"

Line
From "You can either benefit of our <NamedLink name="BirthdayDealPage">Birthday Gift</NamedLink> or you can reward your employees and colleagues with our <NamedLink name="CorporateDealPage">Corporate Benefit</NamedLink>."
To "You can either benefit of our <NamedLink name="BirthdayDealPage">Birthday Gift</NamedLink>, you can reward your employees and colleagues with our <NamedLink name="CorporateDealPage">Corporate Benefit</NamedLink> or you can get a €15 gift card with our <a href="https://www.whichost.com/benefits/recommend-gift" target="_blank">Recommend Reward</a>."

Line
From "Contact us."
To "Still have questions?"

**How should it look like (screenshot or sketch)**:

Title
From "Part of our culture is giving back"
To "Giving back is in our culture"

Line
From "At Whichost we spent days and nights contemplating about how we can further benefit the community. We turn general ideas into presentations and finally into actions."
To "At Whichost we spent days and nights contemplating how we can further benefit the community. We turn ideas into presentations and finally into actions."

Line
From "At the moment we have three active benefits for our members. Both are linked to attractive rewards and you can read more on the following benefits pages."
To "At the moment we have three active benefits. All linked to attractive rewards and you can read more on the following pages."

Line
From "Browse pubs and book now!"
To "Find a pub and book it now!"

Line
From "You can either benefit of our <NamedLink name="BirthdayDealPage">Birthday Gift</NamedLink> or you can reward your employees and colleagues with our <NamedLink name="CorporateDealPage">Corporate Benefit</NamedLink>."
To "You can either benefit of our <NamedLink name="BirthdayDealPage">Birthday Gift</NamedLink>, you can reward your employees and colleagues with our <NamedLink name="CorporateDealPage">Corporate Benefit</NamedLink> or you can get a €15 gift card with our <a href="https://www.whichost.com/benefits/recommend-gift" target="_blank">Recommend Reward</a>."

Line
From "Contact us."
To "Still have questions?"

**How should it work (write use case)**:

N/A. Text change only.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Windows, 10, Chrome, latest
**Branch**: Staging

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope please close the issue when you're done and it's ready to be staged.
