### ISSUE TITLE
Improve corporate benefit page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#205]
**What's to be corrected**: 

- Line

From "They get up to €310 with every celebration."
To "They get up to €310 with each of their celebrations."

- Line

From "This is a physical gift card, so we will ask for an address to deliver it."
To "This is a physical gift card, so we will need an address to deliver it."

- Paragraph

From "The value of the gift card depends on the size of the party: from “Up to 30 people” to “201+”, and on the day that it’s held. Celebrations held between Mondays and Wednesdays have a higher value. This is a physical gift card, so we will ask for an address to deliver it."
To "The value of the gift card depends on the size of the party: from “Up to 30 people” to “201+”, and on the day that it’s held. Celebrations held between Mondays and Wednesdays have a higher value. This is a physical gift card, so we will ask for an address to deliver it.

How much will this benefit cost to your organisation? Nothing, because giving back is in our culture!"

- Line

From "We will add €10 to the gift card if they can’t find the pub they want and they recommend it to us, so they can celebrate there."
To "We will add €10 to the gift card if your employees can’t find the pub they want and they recommend it to us, so they can celebrate there."

**How should it look like (screenshot or sketch)**:

![design corporate benefit page](https://user-images.githubusercontent.com/39112974/58167551-187ec800-7c84-11e9-949f-40f734f619e6.jpg)

**How should it work (write use case)**:

N/A. Text improvement.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Windows, 10, Chrome, latest
**Branch**: Staging

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope please close the issue when they're on staging.

> Please use the prepared answer as below, that will gives you the step:
> 
> **What have been done**: 
> **Pushed to**: (branch)
> **Tag somebody**: 
> **PR**: (create a PR if the branch is ready to be merged)
> 
> **Asking for validation**: 
> 
> - Check on mobile and on desktop if the issue have been correctly fixed.
> - If everything is correct, move the card to accepted column.
> - If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
> - Move the card to have issues column.
> - Merge (or express approval in) the corresponding PR if nee

ded. Move the card to the launch column.

**Comment by RohrerHope** [comment]
**What are the changes**

- Line

From "Give your employees a gift card to use with over 2,000 shops in Ireland & the UK!"
To "Earn a gift card to use with over 2,000 shops in Ireland & the UK!"

- Line

From "They get up to €310 with every celebration."
To "Get up to €310 with each of your celebrations."

- Button CTA

From "CONTACT US FOR MORE INFO"
To "FIND A PUB FOR YOUR CELEBRATION"

- Link in button

From "https://www.whichost.com/help/contact-us"
To "https://www.whichost.com/s?address=Ireland&bounds=55.36%2C-5.911%2C51.427%2C-10.382&origin=53.357%2C-7.756"

- New Line, First Paragraph

"Use your organisation email in your Whichost account, and that's it! You are ready to enjoy our Corporate Benefit."

- Line

From "We will add €10 to the gift card if they can’t find the pub they want and they recommend it to us, so they can celebrate there."
To "We will add €10 to the gift card if you can’t find the pub you want and you recommend it to us, so you can celebrate there."

This is how the page looks today:

![Corporate benefit as it is now](https://user-images.githubusercontent.com/39112974/58713572-c1cb6980-83ba-11e9-9521-1c71614b067c.jpg)

This is the proposed version with the above modifications:

![Corporate benefit proposed](https://user-images.githubusercontent.com/39112974/58713591-ce4fc200-83ba-11e9-8213-9e4ad303dbdc.jpg)

Thank you 👍

**Comment by RohrerHope** [comment]
PR requested
