### ISSUE TITLE
Change the background image

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#210]
**What's the improvement**: 

The main background image we have on our platform.

This is how it looks now if we already had the new search bar:

![Landing page background image 002](https://user-images.githubusercontent.com/39112974/58384970-b7d3f000-7fe1-11e9-97bc-c9c4086e5861.jpeg)

**How should it look like (screenshot or sketch)**:

This is the new image we should implement: https://unsplash.com/photos/nF8xhLMmg0c 

This is how it would look like if we already had the new search bar:

![Landing page background image 003](https://user-images.githubusercontent.com/39112974/58385121-3da46b00-7fe3-11e9-8695-4d804c44d3a7.jpeg)

In order for the white text to be read properly, the image has to be slightly darkened.

Please notice the location of the faces in relation to the search bar when putting the image in the background. There will be some adjusting/cropping so that the faces are in that position.

You can download the image of the three women smiling (the slightly darker version) here: https://drive.google.com/file/d/1nC_LrHHbjo43ToDYQ9utWR6K2Qcz2NL0/view?usp=sharing

**How should it work (write use case)**:

Should work in such a way that we can still read the words without any problem.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: Staging

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by RohrerHope** [comment]
> **What's the improvement**:
> 
> The main background image we have on our platform.
> 
> This is how it looks now if we already had the new search bar:
> 
> ![Landing page background image 002](https://user-images.githubusercontent.com/39112974/58384970-b7d3f000-7fe1-11e9-97bc-c9c4086e5861.jpeg)
> 
> **How should it look like (screenshot or sketch)**:
> 
> This is the new image we should implement: https://unsplash.com/photos/nF8xhLMmg0c
> 
> This is how it would look like if we already had the new search bar:
> 
> ![Landing page background image 003](https://user-images.githubusercontent.com/39112974/58385121-3da46b00-7fe3-11e9-8695-4d804c44d3a7.jpeg)
> 
> In order for the white text to be read properly, the image has to be slightly darkened.
> 
> Please notice the location of the faces in relation to the search bar when putting the image in the background. There will be some adjusting/cropping so that the faces are in that position.
> 
> You can download the image of the three women smiling (the slightly darker version) here: https://drive.google.com/file/d/1nC_LrHHbjo43ToDYQ9utWR6K2Qcz2NL0/view?usp=sharing
> 
> **How should it work (write use case)**:
> 
> Should work in such a way that we can still read the words without any problem.
> 
> **Priority (tag accordingly):** Regular
> **Domain (tag accordingly):** Frontend
> **Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
> **Branch**: Staging
> 
> **Work on it**
> 
> * Derive the branch from `staging`.
> * Tag with `ongoing` and move the card to `ongoing`.
> * Develop the feature
> * Commit your work
> * Create a PR and ask for validation. Move the card to `staged`.
> * Ask for validation.
> * Close the issue if all the work have been done
> 
> ** Validate **
> 
> * Check on mobile and on desktop if the feature have been correctly implemented.
> * If everything is working fine, move the card to`accepted` column.
> * If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.
> 
> Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

@lcoenen @Shane-Walsh 

I've updated the issue.
