### ISSUE TITLE
Change the cookie policy links

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#212]
**What's to be corrected**: 

The link we provide in the cookie banner takes us to the Squarespace cookie page. It needs to take us to our cookie page, here in the platform.

**How should it look like (screenshot or sketch)**:

Our cookies explanation is included in our Privacy Policy, so we should point our visitors to this link: https://www.whichost.com/legal/privacy-policy.

**How should it work (write use case)**:

N/A. It's a change of link for the cookie policy.

**Priority (tag accordingly):** Urgent
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: Master

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by RohrerHope** [comment]
> **What's to be corrected**:
> 
> The link we provide in the cookie banner takes us to the Squarespace cookie page. It needs to take us to our cookie page, here in the platform.
> 
> **How should it look like (screenshot or sketch)**:
> 
> Our cookies explanation is included in our Privacy Policy, so we should point our visitors to this link: https://www.whichost.com/legal/privacy-policy.
> 
> **How should it work (write use case)**:
> 
> N/A. It's a change of link for the cookie policy.
> 
> **Priority (tag accordingly):** Urgent
> **Domain (tag accordingly):** Frontend
> **Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
> **Branch**: Master
> 
> **Work on it**
> 
> * Work on `staging` or `master` (if it's `urgent`)
> * Tag with `ongoing` and move the card to `ongoing`.
> * Correct the default
> * Commit your work
> * Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
> * Close the issue if all the work have been done
> 
> ** Validate **
> 
> * Check on mobile and on desktop if the default have been correctly corrected.
> * If everything is working fine, move the card to`accepted` column.
> * If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.
> 
> Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

@lcoenen @Shane-Walsh 

Issue has been updated.

**Comment by RohrerHope** [comment]
@lcoenen @Shane-Walsh 

This issue was created 12 days ago! It is marked as urgent. Where is the urgency of solving this then?

This is what our visitors see today:

![Annotation 2019-06-05 115845](https://user-images.githubusercontent.com/39112974/58951551-505c3400-8789-11e9-8a31-2673e102457c.jpg)

Why?

**Comment by lcoenen** [comment]
**What have been done**: Correct the link
**Pushed to**: `master`
**Tag somebody**: @Shane-Walsh 
**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.
