### ISSUE TITLE
Change party time from 24 hours format to PM

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#220]
**What's to be fixed**:

1. Originally the party time in the booking page was requested with PM format because in Ireland we use PM, not 24 hours format. However, for some reason, the party time is in 24 hours format.

![Screen Shot 2019-06-01 at 19 03 59](https://user-images.githubusercontent.com/39112974/58752058-4348f780-84a0-11e9-8dfc-9bde89458cd3.jpg)

![Screen Shot 2019-06-01 at 19 04 07](https://user-images.githubusercontent.com/39112974/58752062-46dc7e80-84a0-11e9-9fbb-48af3e46a37d.jpg)

2. Another issue here is the error message where it says "12PM". The PM must be separated from the number. A space in between them. It should say "12 PM".

**What's the expected behavior:**

1. The time format must be AM/PM, not 24 hours format. We clearly must indicate in the party time slot the PM. Meaning, users can only book in PM hours, not AM.
1. "12PM" must be "12 PM". And forever, anywhere where we use AM/PM formatting, AM or PM must be separated by a space from the number.

**What happens in reality (screenshot):**

![Screen Shot 2019-06-01 at 19 03 59](https://user-images.githubusercontent.com/39112974/58752073-7095a580-84a0-11e9-92a5-0cfa621ce512.jpg)

![Screen Shot 2019-06-01 at 19 04 07](https://user-images.githubusercontent.com/39112974/58752076-75f2f000-84a0-11e9-9539-af678c18b899.jpg)

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: `change-party-time-from-24-hours-format-to-PM`
**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

** Validate **

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope 

The behaviour of this field depends on your locals. It is a native behaviour handled by the browser. I just set my computer to use the 12 hour format and this is correctly reflected on the website (on Chrome). I believe we should let the user decide. 

<img width="660" alt="image" src="https://user-images.githubusercontent.com/1237971/59059120-1167d480-8896-11e9-906f-85f477b2e0fd.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/1237971/59059130-162c8880-8896-11e9-813c-d6fb472e05b7.png">

However, we can integrate this: 

https://material-ui-pickers.dev/demo/timepicker

The work is ongoing

**Comment by lcoenen** [comment]
**What have been done**: We integrated @material-ui/pickers for better UX
**Pushed to**: `change-party-time-from-24-hours-format-to-PM`
**Tag somebody**: @Shane-Walsh 
**PR**: #229 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by Shane-Walsh** [comment]
After reimplementing this feature and testing on whichost-frontend-staging - Cannot POST / error occurred.
