### ISSUE TITLE
Clean the logos view at the top of the page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#222]
**What's to be fixed**:

For some reason, at the top of the booking page, there are 2 logos. The icon and the full logo.

![Screen Shot 2019-06-01 at 19 03 19](https://user-images.githubusercontent.com/39112974/58752245-9d978780-84a3-11e9-979c-5503510ff2c8.jpg)

**What's the expected behavior:**

Only the full logo should be seen here. The icon has no place on this page. It's bad design to have the two of them together there.

**What happens in reality (screenshot):**

![Screen Shot 2019-06-01 at 19 03 19](https://user-images.githubusercontent.com/39112974/58752253-d172ad00-84a3-11e9-9eec-a5c9e92c811c.jpg)

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: hotfix-logo-icon-top-page

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

** Validate **

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by Shane-Walsh** [comment]
**Topbar Mobile Logo**

Mobile logo would not respond to CSS on CheckOutPage, so as a fix for now the desktop logo is displayed on the TopBar. 

![#222](https://user-images.githubusercontent.com/20372577/59219274-fceb4b00-8bb9-11e9-8969-b460b8be7ab9.png)

**New Logos**

All these logos will be replaced with the new logo set soon. So, I will have another look at this issue at that point
