### ISSUE TITLE
Improve how much to how many people in party booking

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#223]
**What's to be fixed**:

@lcoenen 

This had already been fixed some time ago! Why is it back here?

![Screen Shot 2019-06-01 at 19 34 20](https://user-images.githubusercontent.com/39112974/58752300-72f9fe80-84a4-11e9-9d9f-af5fe6e76ba4.jpg)

That's bad grammar! It's not "How much people are coming..." it's "How many people...." 

**What's the expected behavior:**

The correct usage of language is "How many people..." not "How much people...."

**What happens in reality (screenshot):**

That question must say: "How many people are coming?"

Again, this had already been fixed in the past. I don't understand why is it back here and this needs to stop. What we fix must stay in the platform and not disappear.

**First impressions matter! Much more than you think! Please, guys, use proper grammar and if you are not sure about the grammar, then use Grammarly (it's free!) to double check!**

**Priority (tag accordingly):** Urgent
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: hotfix-much-is-actually-many

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

** Validate **

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope 

It is a mistake during the merge. You have to understand that each modification create a new version of the code and that it gets harder and harder to keeps track on everything when we modify things too often.

**Comment by lcoenen** [comment]
The issue have been correctly implemented / fixed.
