### ISSUE TITLE
Fix the Common Space type on listings list

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#224]
**What's to be fixed**:

![Annotation 2019-06-05 114847](https://user-images.githubusercontent.com/39112974/58951141-4c7be200-8788-11e9-89cf-5bab2777e570.jpg)

This was working fine and now it's not.

Questions:

1. When is this going to stop? When are we going to stop bringing bugs that were never there in the first place? Or bugs that had already been fixed and now they are back?

1. When are we going to have a process that guarantees that these things don't happen again? Why is staging not the cleanest of all versions, the most updated and the exact clone of master so when pushing to master we don't push crap to it?!

This does not help guys! Does not help with the first impression from users! Does not help with the first impression from the companies we are contacting! Does not help at all because users move away almost immediately from buggy products.

**I'm not asking for everything to be perfect. I'm only asking for it to be clean and for these stresses to be removed from our work because they happen way too often!** 

**What's the expected behaviour:**

The message in those blue boxes must say "Common Space"

**What happens in reality (screenshot):**

![Annotation 2019-06-05 114847](https://user-images.githubusercontent.com/39112974/58951176-5d2c5800-8788-11e9-9bc4-5552be81135c.jpg)

**Priority (tag accordingly):** Urgent
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Windows, latest, Chrome, latest
**Branch**: hotfix-space-type-listing-list

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

** Validate **

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
I am working on it. 

**Work on it**:

- Place the card in `ongoing` column
- Tag it with `ongoing`

**Comment by lcoenen** [comment]
**What have been done**: Add the missing translation
**Tag somebody**: @RohrerHope 
*Pushed on**:  `master`
**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.
