### ISSUE TITLE
Fix next step to Photos in listing a pub

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#228]
**What's to be fixed**:

![Screen Shot 2019-06-06 at 19 15 19](https://user-images.githubusercontent.com/39112974/59060303-b5eb1600-8898-11e9-94ea-1c8eccc8760f.jpg)

See the issue there? The next step is Photos, not Availability. However, the button says Availability.

That issue was not there before. Another issue that was not there before and all of the sudden is.

**What's the expected behavior:**

![Screen Shot 2019-06-06 at 20 24 38](https://user-images.githubusercontent.com/39112974/59060493-26923280-8899-11e9-8ab8-95e004189197.jpg)

In that step, the button should say Next: Photos.

**What happens in reality (screenshot):**

![Screen Shot 2019-06-06 at 19 15 19](https://user-images.githubusercontent.com/39112974/59060377-e337c400-8898-11e9-88ac-9ebaadec5ce2.jpg)

**Priority (tag accordingly):** Urgent
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: hotfix-next-step-photos

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

** Validate **

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
> Another issue that was not there before and all of the sudden is.

This comes from the merge with upstream. I had to remove availability since we don't have a private/common space mechanism implemented yet. This have gone through our attention. Thanks for reporting.

**Comment by lcoenen** [comment]
@RohrerHope This is not a bug but a trivial matter (it's only a translation to change).

**Comment by lcoenen** [comment]
**What have been done**: Correct the translation
**Pushed to**: `staging`
**Tag somebody**: @Shane-Walsh 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.
