### ISSUE TITLE
Change Per Night to Deposit

### ISSUE THREAD

**Issue by Shane-Walsh** [Whichost/frontend#230]
**What's to be fixed**:
- While in booking process, where is should display 'Deposit', it's displaying 'Per Night'
**Expected to display'**
- 'Deposit' instead of "per night'
- Issue definitely occurring on mobile, but check on all platforms
![issue-per-night](https://user-images.githubusercontent.com/20372577/59067985-eb006400-88aa-11e9-862b-db80d74600af.jpg)

**Priority**  (`backlog` column)
**Domain (tag accordingly):** `frontend` 
**Tested on:** (platform, OS, browser, version)
**Branch**: derive from staging

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

** Validate **

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by Shane-Walsh** [comment]
**To be fixed** 

On checkout page "per night" is displayed under provider name instead of "deposit" - see img below:

![#230-checkoutPage](https://user-images.githubusercontent.com/20372577/59297287-d55eb600-8c7f-11e9-875a-39ccdefc0fb5.png)

**Comment by scottyzen** [comment]
**Update**
I have updated to the checkout page. 'Deposit' is displaying now.
