### ISSUE TITLE
Implement User Fee Donation Page

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#240]
**What's the improvement**: 

In the interest of providing more exposure to our donation of the user fee, this feature is to create a page dedicated to it, inside the Benefits page.

The location of the page in the left menu I would put it right below the "What's this", so it's first there, showing how important that's to us.

I used Inspect to create the prototype by replacing the content of one of the pages, so do not think that I'm deleting a page here, I'm just giving you guys the content and idea.

Here's the proposed idea:

![Fees donation page](https://user-images.githubusercontent.com/39112974/59337958-69209880-8cf9-11e9-940a-67e5a707a684.jpg)

**How should it look like (screenshot or sketch)**:

The proposed idea involves putting this page right after the "What's this" on the left menu.

![Fees donation page](https://user-images.githubusercontent.com/39112974/59337977-7047a680-8cf9-11e9-9e02-f78dd46a7d2c.jpg)

**How should it work (write use case)**:

This would involve the need to change the footer menu under "Customers" called today "Benefits for you". We need to change this to "Benefits" only. So it's all benefits, not only those for you. ;) 

If you believe the text can be improved, by all means, please propose your text improvements.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Windows, latest, Chrome, latest
**Branch**: Staging

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by scottyzen** [comment]
I have added this page. https://github.com/Whichost/frontend/pull/254
