### ISSUE TITLE
Fix the values submitted by StripePayementForms

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#243]
**What's to be fixed**:

The StripePayementForm isn't correctly sending values. It prevent those values to be recorded and the booking Breakdown to show those values.

**What's the expected behavior:**

The values should be correctly stored.

**What happens in reality (screenshot):**

The `StripePayementForm().handleSubmit()` used to receive the values from FinalForms. For unknown reason, this function now receive the `event` object, that is not preventing default behavior (that was the reasons for `Cannot POST /`).

Now, we have to retrieve where those datas are stored.

See https://github.com/final-form/react-final-form

I fixed that, but now the values aren't updated anymore.

**Priority (tag accordingly):** `urgent`
**Domain (tag accordingly):** `frontend`
**Tested on:** Every platform
**Branch**: `hotfix-fix-values-submitted-by-stripe-payement-forms`
**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

**Validate**

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
![image](https://user-images.githubusercontent.com/1237971/59381142-ac5b2580-8d52-11e9-82c1-4bbd38fd63d5.png)

This is definitely from them.

**Comment by Shane-Walsh** [comment]
Can we email them about this, who is their point of contact?

**Comment by lcoenen** [comment]
I would ask on their Slack

**Comment by lcoenen** [comment]
This is the file after we added the time field. As you can see, we're recreating the `values` object from the state. 


https://github.com/Whichost/frontend/blob/aefbca354b1ab7ffa793aff6febfa88406233961/src/forms/StripePaymentForm/StripePaymentForm.js

I wondered what changed. I copied those lines but now I have an error with @material-ui.

Work ongoing
