### ISSUE TITLE
Improve search help in mobile

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#245]
**What's the improvement**: 

When going to search on mobile, the help message is not very aligned with the fact that we operate in Ireland and the UK.

This the message:

![Screen Shot 2019-06-13 at 19 38 47](https://user-images.githubusercontent.com/39112974/59458753-07ece800-8e13-11e9-888b-f60d43e3a379.jpg)

**How should it look like (screenshot or sketch)**:

![Screen Shot 2019-06-13 at 19 41 32](https://user-images.githubusercontent.com/39112974/59458875-54d0be80-8e13-11e9-8fbe-1c164a57a18f.jpg)

**How should it work (write use case)**:

N/A. Text improvement.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: Staging

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by RohrerHope** [comment]
PR #246 

Thanks 👍

**Comment by lcoenen** [comment]
@RohrerHope please remember to create the card on the project so we can keep track of what have been changed :)
