### ISSUE TITLE
Take down "We're hiring" page

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#248]
**What's to be corrected**: Can someone please take down the “We’re hiring” page and remove the link in the footer? Got some negative feedback about it being still online but we’re not hiring anymore.
**How should it look like (screenshot or sketch)**:
![image](https://user-images.githubusercontent.com/1237971/59551129-c7a17d00-8f6c-11e9-9521-67e707793ca7.png)
**How should it work (write use case)**:
NA
**Priority (tag accordingly):** `urgent`
**Domain (tag accordingly):** `frontend`
**Tested on:** NA
**Branch**: (commit directly to `staging` / PR to `master` if it's `urgent`)

**Work on it**

- Work on `staging` or `master` (if it's `urgent`)
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

**Validate**

- Check on mobile and on desktop if the default have been correctly corrected.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by Shane-Walsh** [comment]
The "We're hiring" link still present. 

![hiring-issue-#248](https://user-images.githubusercontent.com/20372577/60136024-0b7d5900-979b-11e9-94ef-640331f5286d.png)

**Comment by scottyzen** [comment]
Yea it must not have pushed. Can you check again
