### ISSUE TITLE
Change Common Space to Shared Space and Filter Title

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#288]
**What's the improvement**: 

The most common expression used in other marketplaces is shared and not common. That's why we can improve this.

This is what we have today:

![Screen Shot 2019-07-28 at 09 39 29](https://user-images.githubusercontent.com/39112974/62004358-d8244600-b11b-11e9-8c20-305a837e2f91.jpg)

And this is the proposal:

![Screen Shot 2019-07-28 at 09 37 54](https://user-images.githubusercontent.com/39112974/62004360-e2464480-b11b-11e9-80d8-5167a77124b7.jpg) 

**How should it look like (screenshot or sketch)**:

Wherever we use the expression Common Space, we need to change it to Shared Space.

![Screen Shot 2019-07-28 at 09 37 54](https://user-images.githubusercontent.com/39112974/62004367-fd18b900-b11b-11e9-93c9-77028ee478eb.jpg)

**How should it work (write use case)**:

This is merely a text change. Make sure it is applied in all areas of the platform where it's used.

**Priority (tag accordingly):** Regular (before YC application)
**Domain (tag accordingly):** Frontend (backend maybe? Don't know)
**Tested on:** (platform, OS, browser, version) Mac, latest, Chrome, latest
**Branch**: Staging

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by RohrerHope** [comment]
For the title of the filter, we also need to make it more clear, by changing from "Type" to "Type of space".

This is what we have today:

![Screen Shot 2019-07-28 at 09 45 43](https://user-images.githubusercontent.com/39112974/62004401-8cbe6780-b11c-11e9-887e-901b1bb96c63.jpg)

And this is the proposal:

![Screen Shot 2019-07-28 at 09 45 30](https://user-images.githubusercontent.com/39112974/62004404-934cdf00-b11c-11e9-9a94-977955f2eacf.jpg)

Also, anywhere else where this filter title is used, we need to make sure to change it.

**Comment by scottyzen** [comment]
I changed it to "Space type". ✅
