### ISSUE TITLE
Capacity of Pub not being saved (and Opening Days)

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#31]
@lcoenen 

When creating a listing, the capacity of the listing is not being saved.

I'm attaching how it looks before saving the capacity and what happens after saving.

This is what looks like before saving:
![screen shot 2019-01-31 at 20 03 05](https://user-images.githubusercontent.com/39112974/52082017-96af4580-2593-11e9-92fe-82a6fecac9d0.jpg)

This is what it looks like after saving:
![screen shot 2019-01-31 at 20 03 14](https://user-images.githubusercontent.com/39112974/52082038-a0d14400-2593-11e9-8614-f2334b236acd.jpg)

The same thing happens with the Opening Days section.

**Comment by lcoenen** [comment]
This is confirmed. This is working fine with amenities, and is probably link with the state not being updated correctly. Reopening the corresponding branch will be necessary.

**Comment by lcoenen** [comment]
This is downstream from `src/components/EditListingWizard/EditListingWizardTab.js` 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/1237971/52175706-caf75180-279f-11e9-9d3d-9881abaa11a5.png">

The underlying components (`EditListingCapacityPanel`) is returning an empty array whatever we click on.

**Comment by lcoenen** [comment]
This is what is returned by `EditListingCapacityForm.onSubmit()`. 

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1237971/52175742-4527d600-27a0-11e9-976f-460fc852de2f.png">

It looks like the issue is a mix up between `groupSize` and `capacity` vars name.

**Comment by lcoenen** [comment]
This have been fixed.
