### ISSUE TITLE
Birthday not being saved

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#32]
@lcoenen 

Before saving the birthday:
![birthday before saving](https://user-images.githubusercontent.com/39112974/52082708-6e284b00-2595-11e9-9ace-db8a59e4e2e4.png)

After saving the birthday:
![birthday after saving](https://user-images.githubusercontent.com/39112974/52082721-77b1b300-2595-11e9-966a-43f1dedb1247.png)

Not saved.

**Comment by RohrerHope** [comment]
When making changes and saving the information inside Flex, when the Saving action is successful the Saving button changes to a Checkmark before the page loads again.

When the saving is not successful, like in this case, the save button stays grey.

![screen shot 2019-01-31 at 21 08 21](https://user-images.githubusercontent.com/39112974/52085501-923b5a80-259c-11e9-91c5-8df7b28fc310.jpg)

**Comment by lcoenen** [comment]
This is confirmed. It should be an issue in `src/containers/ProfileSettingsPage`

**Comment by lcoenen** [comment]
Ok, I don't get how the values are correct in the first place when `currentUser` is `null` in `ProfilePage.js`
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1237971/52175998-95a13280-27a4-11e9-9573-1b5d127ffd9d.png">

**Comment by lcoenen** [comment]
Ok, so the render function is executed several time (before and after loading), that's where those value came from. The system is now saving and retrieving the birthday correctly, but still not showing it inside the form. 

Also, what will we do with the missing values? I guess the easier will be to ask for the birthday at signup.

**Comment by lcoenen** [comment]
The correct date is received by `FieldBirthdayInput` in `this.props.value`. Yet, this isn't shown correctly.

**Comment by lcoenen** [comment]
Everything have been fixed. The birthday is now asked at signup and the platform won't let you signup if you're not 18.
