### ISSUE TITLE
18 years of age info not visible inside profile

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#33]
We ask the user if they are 18 years of age or older, but is that information stored? It's no where to be seeing inside the user profile:
![birthday before saving](https://user-images.githubusercontent.com/39112974/52082790-a039ad00-2595-11e9-937f-01ed0eb74af5.png)

We need to not only store that information, but we also need to show it. That information needs also to be public, so P must be able to see it when they are looking at a users profile.

This is exactly how our current platform is setup.

**Comment by lcoenen** [comment]
This is fixed 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1237971/52175510-f0369080-279c-11e9-88ea-05a9303c3db1.png">
