### ISSUE TITLE
Occasion not showing anywhere is the full view of the requests from the P point of view

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#35]
@lcoenen 

This is the full view of the request from the P point of view:
![screen shot 2019-01-31 at 20 57 29](https://user-images.githubusercontent.com/39112974/52084876-f2310180-259a-11e9-86a0-64382ea907ce.jpg)

As a P, nowhere I can see the occasion of this booking request. This information is important and needs to be here.

**Comment by lcoenen** [comment]
Duplicate as in #36
