### ISSUE TITLE
Occasion not showing anywhere in the user view after sending the request

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#36]
@lcoenen 

This is the view from the user after they sent the request to the P:
![screen shot 2019-01-31 at 20 59 17](https://user-images.githubusercontent.com/39112974/52084957-2dcbcb80-259b-11e9-9069-1e28ead39d4a.jpg)

The occasion of the party is nowhere to be seeing. The occasion must be there.

**Comment by lcoenen** [comment]
This have to be fixed in `src/components/TransactionPanel/TransactionPanel.helpers.js`.

**Comment by lcoenen** [comment]
The occasion isn't even leaving the `StripePayementForms` components

**Comment by lcoenen** [comment]
![image](https://user-images.githubusercontent.com/1237971/52177817-87601000-27be-11e9-851a-02f4bd47befa.png)

**Comment by lcoenen** [comment]
It is still correctly set in `
