### ISSUE TITLE
Put social medias link back

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#37]
![image](https://user-images.githubusercontent.com/1237971/52142823-b016c700-2651-11e9-9579-3c33d8548bf8.png)

This have to go away ASAP.

**Comment by lcoenen** [comment]
This is really weird because it's working locally, but the issue is only on the heroku app.

**Comment by lcoenen** [comment]
Maybe that is linked with this error that keeps happening everywhere 
<img width="913" alt="image" src="https://user-images.githubusercontent.com/1237971/52176259-2a595f80-27a8-11e9-8984-7a1f93e5b539.png">

**Comment by lcoenen** [comment]
I redownloaded the whole repo but it still doesn't appears on my side. Maybe it's a matter of developpement mode?

**Comment by lcoenen** [comment]
The issue is also happening on staging when it is set to branch 4a, which means it's not branch related. 

But it is disapearing when we remove `{socialMediaLinks}` in `Footer.js`
![image](https://user-images.githubusercontent.com/1237971/52413439-8d653200-2ad9-11e9-82e2-65b08db8e468.png)

**Comment by lcoenen** [comment]
When I add the term "WTF" after the facebook link, and it didn't show in orange. Why?
![image](https://user-images.githubusercontent.com/1237971/52429992-01fd9800-2afd-11e9-8204-9f24ab5a66b6.png)

**Comment by lcoenen** [comment]
![image](https://user-images.githubusercontent.com/1237971/52430720-a3d1b480-2afe-11e9-8b28-e33ae4b1156a.png)
@buckwierd could you have a look at that? :)

**Comment by lcoenen** [comment]
The social links have been removed for now... But we'll still have to understand wtf is going on

**Comment by lcoenen** [comment]
I put the links back. @RohrerHope could you check on the floating server (set on `put-social-media-links-back`). 

The address is https://whichost-frontend-float.herokuapp.com/

**Comment by RohrerHope** [comment]
The issue still there.

Desktop:

![Screen Shot 2019-04-11 at 20 31 41](https://user-images.githubusercontent.com/39112974/55987220-ecd9ec80-5c98-11e9-85fb-12b1c9d31f44.jpg)

Mobile:

![Screen Shot 2019-04-11 at 20 32 00](https://user-images.githubusercontent.com/39112974/55987228-f400fa80-5c98-11e9-9a8f-e925eba876a9.jpg)


I still believe that the "Top Cities" column in the footer is the one mixing everything up.

**Comment by lcoenen** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/1237971/55987422-6e317f00-5c99-11e9-9abd-32d2b676d79d.png">
 
This is how it looked in my browser :/

**Comment by lcoenen** [comment]
@RohrerHope what browser are you using?

**Comment by RohrerHope** [comment]
Chrome latest version with Mac OS latest version.

**Comment by lcoenen** [comment]
What about mobile?

**Comment by RohrerHope** [comment]
Chrome latest version on iOS latest version.

**Comment by RohrerHope** [comment]
On my iPhone view.

Vertical view:

![IMG_1508](https://user-images.githubusercontent.com/39112974/55987769-25c69100-5c9a-11e9-968a-85782378c79b.PNG)

Horizontal view:

![IMG_1509](https://user-images.githubusercontent.com/39112974/55987781-2e1ecc00-5c9a-11e9-8333-8da20111206a.PNG)

Chrome, latest version.

**Comment by lcoenen** [comment]
For the record, here is how it looks on Safari (on localhost) 

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/1237971/55987827-48f14080-5c9a-11e9-871f-6cf959b38029.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/1237971/55987857-53abd580-5c9a-11e9-9d99-ac390316d5e6.png">

**Comment by lcoenen** [comment]
But set on a distant address, this is what I get (Safari 12.0.3). 
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/1237971/55987926-805fed00-5c9a-11e9-9280-fea3a36105e4.png">

**Comment by RohrerHope** [comment]
We clearly don't have this figured out yet.

Please let's continue with other tasks we have at hand.

**Comment by lcoenen** [comment]
So the link is in orange because it's defined in `marketplaceIndex.css`
```
body {
  font-family: 'Lato', sans-serif;
  -webkit-font-smoothing: antialiased; /* http://szafranek.net/blog/2009/02/22/font-smoothing-explained/ */
  -moz-osx-font-smoothing: grayscale; /* http://szafranek.net/blog/2009/02/22/font-smoothing-explained/ */
  text-rendering: optimizeSpeed;

  background-color: #fcfcfc;
}

::-moz-selection {
  background: #ff3f00; /* WebKit/Blink Browsers */
  color: #ffffff;
}

::selection {
  background: #ff3f00; /* WebKit/Blink Browsers */
  color: #ffffff;
}
```
![image](https://user-images.githubusercontent.com/1237971/56222068-43fa0b80-6063-11e9-9854-d3d6a914398f.png)

**Comment by lcoenen** [comment]
I asked sharetribe, the misplacement issue is due to a width defined here: 
![image](https://user-images.githubusercontent.com/1237971/56222760-7bb58300-6064-11e9-924d-dcb83a788b28.png)

They cannot tell me why I don't see the same thing on `localhost` and on the distant server.

**Comment by lcoenen** [comment]
Also, the links in `src/components/Footer/Footer.js` all have the same `className`? I wonder if it's related.

![image](https://user-images.githubusercontent.com/1237971/56223064-f41c4400-6064-11e9-829b-7f11d850b048.png)

@buckwierd could you have a look? Please be careful about the class you're using (in your defence it was before I explained JSX to yo)

![image](https://user-images.githubusercontent.com/1237971/56223138-1ada7a80-6065-11e9-8563-bd1190b9941a.png)

**Comment by lcoenen** [comment]
![image](https://user-images.githubusercontent.com/1237971/56287547-8f202700-6114-11e9-88da-93f8f6161a38.png)

**Comment by lcoenen** [comment]
**What have been done**: Put the social media links back 
**Pushed to**: `put-social-media-links-back`
**Tag somebody**: @RohrerHope 
**PR**: 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by RohrerHope** [comment]
Sorry, I don't know how to access this to test it.

Please provide instructions if the URL will not be staging, which is the only one I have saved.

Thanks.

**Comment by RohrerHope** [comment]
Social media icons looking good in both mobile and desktop versions.
