### ISSUE TITLE
[Cosmetic] Text in the How to have a blast section

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#39]
@lcoenen @buckwierd 

![annotation 2019-02-04 080822](https://user-images.githubusercontent.com/39112974/52196755-ef613580-2854-11e9-9c70-7d5fd0ab538c.jpg)

Please update to the following.

1. Browse and book
Start by searching for a location. Once you find a pub you like, requesting a booking with it and make a secure payment right away.
2. Have a great party
Once the request has been accepted you can invite your friends and enjoy your party.
3. Review the host
After enjoying the experience, let others know by reviewing your host. Help others know where to go.

Those are small text improvements, not only on how we say it, but also in the grammar part of it.

**Comment by buckwierd** [comment]
@RohrerHope please check number 1. 
The part starting with "requesting a booking" doesn't make sense. Should maybe "requesting" mean "request" or did you had another sentence in mind?

**Comment by RohrerHope** [comment]
@buckwierd you are correct, it's "request". 

Thanks.

**Comment by buckwierd** [comment]
On it.

**Comment by buckwierd** [comment]
Done and pushed.

@RohrerHope from 1. I've removed "with it" due to double confirmation. Explanation: After you've found a pub that you like, "request a booking" is already saying that the booking is with the pub you like. "With it" is too much and gives the sentence a weird taste.
