### ISSUE TITLE
[Cosmetic] Favicon is still the blue icon

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#40]
![annotation 2019-02-04 081709](https://user-images.githubusercontent.com/39112974/52196862-51219f80-2855-11e9-97ae-93e60d865a96.jpg)

@lcoenen @buckwierd 

This has been reported at least twice before guys.

Please update the favicon to our orange icon.

**Comment by buckwierd** [comment]
Looks like it was done. I allow myself to close this issue as completed.
