### ISSUE TITLE
[Cosmetic] Enter your birthday in sign up not properly aligned

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#42]
![annotation 2019-02-04 082816](https://user-images.githubusercontent.com/39112974/52197283-e1acaf80-2856-11e9-9d3c-18482d0e7983.jpg)

@lcoenen @buckwierd 

Please make sure the "Enter your birthday" text is in the proper line.

Thank you.

**Comment by buckwierd** [comment]
On it.

**Comment by buckwierd** [comment]
@lcoenen I also can't see the "Enter your birthday" area on my localhost, although I fetched the origin. Am I missing something? Can you help?

**Comment by lcoenen** [comment]
On which branch are you?

**Comment by lcoenen** [comment]
The branch 4e have been merged already :/

**Comment by buckwierd** [comment]
Done. Pushed under "4a-adjust-the-static-centent".

**Comment by buckwierd** [comment]
@lcoenen please don't forget to push to master ;)
