### ISSUE TITLE
"Edit listing" doesn't open the L edit page

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#43]
After logging into the account and surfing to "My Listings" page, the button "Edit Listing" opens a blank page instead of the "edit listing" page, after clicking on it.
Same happens when previewing the L and you click on the top right corner on "Edit Listing".

**Comment by lcoenen** [comment]
Opened a new branch 13-edit-listing-error. The issue is 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/1237971/52410532-81c13d80-2ad0-11e9-8232-a5d1ae5b37c6.png">

**Comment by lcoenen** [comment]
This is fixed

**Comment by lcoenen** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/1237971/52429982-fd38e400-2afc-11e9-93cd-bca0c05171bb.png">
<img width="157" alt="image" src="https://user-images.githubusercontent.com/1237971/52430011-0c1f9680-2afd-11e9-9356-b019cf128ff3.png">
