### ISSUE TITLE
Email verification link not working

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#46]
The email verification link is sending the wrong marketplace.url when a new user joined.

This is the build-in code that's being sent out
{{marketplace.url}}/verify-email?t={{form-encode email-verification.token}}

This is how it looks in the new user email
https://www.whichost.com/verify-email?t=8990174860574058

This is how it should look like
https://market.whichost.com/verify-email?t=8990174860574058
without www

IMPORTANT
If we say https://www.market.whichost.com/verify-email?t=8990174860574058 it doesn't work, because of the www

**Comment by buckwierd** [comment]
Quick fixed it by replacing **{{marketplace.url}}** with https://market.whichost.com

**Comment by buckwierd** [comment]
@lcoenen  Needs to be fixed asap so we can put **{{marketplace.url}}** back.

**Comment by RohrerHope** [comment]
@lcoenen 

How are we doing with this? Now that we have the DNS properly set up.

**Comment by lcoenen** [comment]
We are taking the URL back to what they are supposed to be from the first place.

**Comment by lcoenen** [comment]
Duplicate with #89
