### ISSUE TITLE
L admin edit

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#48]
The message that a P is seeing on his L waiting for admin approval is not very user friendly:
“NAME OF THE LISTING is waiting for admin approval and can’t be booked.”

Will be changed to something like:
“Your listing NAME OF LISTING is undergoing our quality check at the moment. This normally takes 48 hours. We’ll get back to you asap and we apologize for any inconvenience that this might have caused.”

Addition:
We could also implement a link to a page with information why we’re quality checking it.

**Comment by lcoenen** [comment]
This have been fixed and put into `staging`
