### ISSUE TITLE
[Cosmetic] Enter your birthday and error message when you are under 18.

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#49]
![screen shot 2019-02-12 at 17 22 37](https://user-images.githubusercontent.com/39112974/52655093-51700980-2eeb-11e9-9893-f858c95dcddc.jpg)

1. The text "You should be at least 18 to use the platform", please make it "You should be at least 18 years of age to use Whichost."

1. The "Enter your birthday" text is still off.

**Comment by RohrerHope** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[C] Implement the birthday deal](https://trello.com/c/xwaFQ4bf/26-c-implement-the-birthday-deal)

**Comment by buckwierd** [comment]
Again: The “Birthday” line was fixed. 
Looks like Loïc didn’t pushed it to master.

**Comment by RohrerHope** [comment]
@lcoenen 

Please your review of this.

And please also adapt the error text. Thanks.

**Comment by RohrerHope** [comment]
@lcoenen 

Any news?

**Comment by lcoenen** [comment]
Again, if you're not telling me which branch to push, I cannot guess it.

**Comment by buckwierd** [comment]
As agreed for small changes, this was also pushed through 4-adjust-the-static-centent 

Since Loïc pushed the 4-adjust-the-static-centent changes in regards to another issue today, the birthday deal is fixed. At least on my side. 

Closing the issue. Please feel free to reopen if something is still not working.

**Comment by buckwierd** [comment]
Reopening since the text mentioned under no. 1 by Carlos is still the old one. Sorry for closing and reopening.

**Comment by lcoenen** [comment]
@buckwierd I pushed the change on `staging`, can we close this issue?

**Comment by lcoenen** [comment]
Still not done into `staging`. To be done ASAP,

**Comment by lcoenen** [comment]
This have been fixed into `staging`
