### ISSUE TITLE
Emails in the deals page do not exist and are not the ones we agreed on

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#50]
@buckwierd 

![screen shot 2019-02-12 at 17 54 58](https://user-images.githubusercontent.com/39112974/52656959-6babe680-2eef-11e9-99b2-e48029a44def.jpg)

The email used here deals@whichost.com does not exist.

We agreed that we would use corporate@whichost.com for the corporate deal, and organisation@whichost.com for the associations/federations.

**Comment by buckwierd** [comment]
I’m really sorry but you’re looking at a wrong version of the platform. Looks like Loic didn’t pushed the changes to master.

**Comment by RohrerHope** [comment]
@lcoenen 

Any news?

**Comment by lcoenen** [comment]
@buckwierd On which branch did you do that? I pushed every commit from the branch `4-adjust-static-content`

**Comment by lcoenen** [comment]
@buckwierd if you want me to push something, you have to tell me. We will switch to a Pull Request workflow soon.

**Comment by buckwierd** [comment]
This was done in #19

**Comment by lcoenen** [comment]
@buckwierd please don't close the issues next time, otherwise I have no way to know I have to merge something :)

**Comment by lcoenen** [comment]
This have been pushed to `staging` and `master`
