### ISSUE TITLE
[Domain DNS] Have www at the marketplace and info at Squarespace

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#52]
As agreed, is to set up our DNS so that www is for the marketplace and info is for the Squarespace pages.

**Comment by RohrerHope** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change CNAMEs for marketplace and Squarespace](https://trello.com/c/G2J5pguz/41-change-cnames-for-marketplace-and-squarespace)

**Comment by buckwierd** [comment]
Labeling as urgent since no one on this planet likes to click on a "WHICHOST" button to see the platform, after already typing www.whichost.com in the browser.

**Comment by buckwierd** [comment]
@Carlos FYI

@Loic
Can you please take care of this as urgent? We keep having issues based on marketplace.url  pointing to incorrect domains

**Comment by lcoenen** [comment]
I can see the label.

**Comment by RohrerHope** [comment]
@lcoenen Would it be possible to take care of this before continuing with other issues?

To at least have the peace of mind that all URLs are in place.

**Comment by lcoenen** [comment]
Right now I am taking care of #57, which is equally severe.

**Comment by RohrerHope** [comment]
> 
> 
> Right now I am taking care of #57, which is equally severe.

Perfect. Then once that is fixed, let's please fix the DNS and the URLs. 👍

**Comment by buckwierd** [comment]
Great 🤙

**Comment by lcoenen** [comment]
@buckwierd your recent email modification have been pushed to `staging`. Could you test on the staging version (https://whichost-frontend-staging.herokuapp.com/) to check if your modification have been pushed?

**Comment by lcoenen** [comment]
In the meanwhile, I am redirecting the footer links to `info.whichost.com`.

**Comment by lcoenen** [comment]
This have been pushed to `staging`.

**Comment by buckwierd** [comment]
Looks like everything works fine. Issue will be closed now. Feel free to reopen it, if work still needs to be done, that I don't know about.
