### ISSUE TITLE
Occasion title too close to previous field.

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#53]
@lcoenen @buckwierd 

The Occasion title is too close to the field above. All the other titles have a proper spacing from the previous field. Please allow that space for the Occasion title.

![screen shot 2019-01-31 at 20 51 11](https://user-images.githubusercontent.com/39112974/52084506-26f08900-259a-11e9-8b7c-36a880281c0e.jpg)

**Comment by lcoenen** [comment]
This have been fixed and pushed to master
