### ISSUE TITLE
Attendance title to have the same colour as the other titles

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#54]
@lcoenen @buckwierd 

The Attendance title, please make it just like the Payment, Message and Occasion titles? (the colour of it)

![screen shot 2019-01-31 at 20 51 11](https://user-images.githubusercontent.com/39112974/52084427-fdcff880-2599-11e9-9aab-c8f9fbe56c45.jpg)

**Comment by lcoenen** [comment]
This have been fixed.
