### ISSUE TITLE
Attendance field has a not so friendly behavior to input the number

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#55]
@lcoenen @buckwierd 

The field to indicate the attendance has a very strange and not friendly behavior. I can't delete the numbers with my keyboard to input new ones.

I can change the number with the arrows on the right (up and down) which are very small arrows.

I can change the number with the keyboard, but only I have figure out how to do it with the keyboard, which our users will not spend time trying to figure out how it works.

![screen shot 2019-01-31 at 20 48 16](https://user-images.githubusercontent.com/39112974/52084356-d416d180-2599-11e9-911f-db134db56e56.jpg)

**Comment by buckwierd** [comment]
I believe this is JS related, so only Loic can assist.

**Comment by RohrerHope** [comment]
@lcoenen 

This needs to be addressed quickly. The behaviour of that field is not user-friendly.

**Comment by RohrerHope** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Whichost deal manually activated for special events](https://trello.com/c/j0Kvejs7/36-whichost-deal-manually-activated-for-special-events)

**Comment by RohrerHope** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Whichost deal manually activated for special events](https://trello.com/c/j0Kvejs7/36-whichost-deal-manually-activated-for-special-events)

**Comment by RohrerHope** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A message to clarify the limit of 10 people for a booking](https://trello.com/c/wuwhS2na/49-a-message-to-clarify-the-limit-of-10-people-for-a-booking)

**Comment by RohrerHope** [comment]
**This Trello card is related to this issue.**

https://trello.com/c/wuwhS2na

The idea in the Trello card saves us the work of creating an error message for groups of less 10 people. We set the expectations up front.

**Comment by lcoenen** [comment]
@RohrerHope This have been fixed and pushed to `staging`, could you check in a few minutes.
@buckwierd could you style this line (in `forms/StripePayementForm/StripePayementForm.js`, line 355)
    
    <p>{this.validAttendance(this.state.attendance)}</p>

and push it on branch `attendance-field-ux-issue`? :)

**Comment by RohrerHope** [comment]
Great work with this field.

Let's please remove the (minimum 10) next to people, since we are explaining properly why, and that explanation is in the error message that will appear anyways. 👍 

So it would look like this:

![screen shot 2019-02-24 at 20 26 34](https://user-images.githubusercontent.com/39112974/53304890-a0665900-3872-11e9-933c-d86c12153a96.jpg)

**Also**

Since that number won't be higher than 500, can we reduce the size of the space to enter the number? Like 5 characters long I believe it's enough, so 10000 would fit in there (as a reference of the number of spaces in that field).

**Comment by RohrerHope** [comment]
**In addition to the comment before**

Please adjust the text size to 15px, make the colour more grey, so full black and bring it closer to the attendance field. I created a reference to give the idea in the image below:

![screen shot 2019-02-24 at 20 32 24](https://user-images.githubusercontent.com/39112974/53304990-b88aa800-3873-11e9-9a21-e834e8bece1a.jpg)

Thank you 👍

**Comment by lcoenen** [comment]
This is ready to go Live but @RohrerHope  is having minor CSS issue
