### ISSUE TITLE
Occasion selector color and behavior

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#56]
@lcoenen @buckwierd 

From the occasion selector:

1. can we improve how it looks like when you are selecting the option? So it looks cleaner.

1. can we make the selection color, not that green? Can we make it our orange with white letters maybe?

![screen shot 2019-01-31 at 20 45 16](https://user-images.githubusercontent.com/39112974/52084175-58b52000-2599-11e9-991f-6e9b64ed652f.jpg)

**Comment by buckwierd** [comment]
1. Technically possible but I'm not sure if it's only CSS. I'll check it out.
2. Will do

**Comment by lcoenen** [comment]
Do you have any idea on the how to improve it or how it should look?

**Comment by RohrerHope** [comment]
I'll try to come up with something. I'll get back to you on this.

**Comment by RohrerHope** [comment]
I can't find a way to modify it via CSS with Inspect. I can't even find the element that is determining the background colour when choosing an option.

I won't be of much assistance with this one.

If you use it, you will see that the UX is not very pleasant since it looks out of sync with the overall form. The width does cover the entire field, as you can still see the arrow on your right.

So maybe small fixes to it, and updating the selection colour would be enough for now.

Thanks 👍

**Comment by buckwierd** [comment]
On my end the dropdown has a normal standard drop down behaviour:
- Simple list
- Blue bg for the hovered option

@RohrerHope the only thing I can do here at the moment is to optimise the padding at the top

**Comment by buckwierd** [comment]
@RohrerHope We could also change the color of the title liek Payment, Message, Occasion etc. to orange, to make them more visible. Agree or will we leave them grey?

**Comment by RohrerHope** [comment]
@buckwierd 

I'll play with the css regarding the title colours and get cable to you. Not today most probably.

Thanks.

**Comment by RohrerHope** [comment]
This is how it looks now

![titles in grey](https://user-images.githubusercontent.com/39112974/53009722-06e31580-3434-11e9-9a7b-05b235b3c679.jpg)

This is how it would look like with titles in our orange

![titles in orange](https://user-images.githubusercontent.com/39112974/53009747-12ced780-3434-11e9-8c51-3c59cf11bc68.jpg)

I like how the orange titles look like.

If we move forward with that option, then other titles in the platform are also greyed out, so we need to check for those and change them as well.

Thanks 👍

**Comment by buckwierd** [comment]
The other titles will be automatically updated after we changed the global grey color that’s connected to these type of titles. 

The color grey is defined by 4-6 shades in the global color file, so we’ll have to change one, see which titles are affected and then decide if we send it to master or revert it.

**Comment by RohrerHope** [comment]
Sounds good.

BTW, about the occasion selector. It now looks different than in the original screenshot I posted. It looks cleaner.

Did anyone change anything in it?
