### ISSUE TITLE
Listing Type haven't been migrated

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#58]

**Comment by lcoenen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[All users - Essential] Replicate our fields and filters from Go to Flex.](https://trello.com/c/1Eb7wgmY/22-all-users-essential-replicate-our-fields-and-filters-from-go-to-flex)

**Comment by lcoenen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[C] Make the listing react to the type (common or private).](https://trello.com/c/WDDKxxM6/37-c-make-the-listing-react-to-the-type-common-or-private)

**Comment by RohrerHope** [comment]
If they haven't been migrated then how do I see the Common Spaces live in our marketplace? Before they were all private and now they are common, which is what we wanted.

What is missing?

Asking just to understand. 👍

**Comment by lcoenen** [comment]
@RohrerHope By default, if the information is not there, the system is considering the pub to be `common`.

**Comment by lcoenen** [comment]
Nevermind, they fixed it.
