### ISSUE TITLE
Remove justification of texts

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#60]
Let's please remove the text justification from our platform.

Text justification is not a best practice when it comes down to websites and platforms. It may look good and professional on paper, but on the web, it creates text gaps that do not look good.

Reference:
[Justify text with HTML/CSS? Don’t do it!](https://designforhackers.com/blog/justify-text-html-css/)

Samples of famous platform and websites that do not justify their web texts:
Stripe.com
![img_1470](https://user-images.githubusercontent.com/39112974/52773233-686d4380-3032-11e9-9727-120887785c8a.PNG)

Uber.com
![uber](https://user-images.githubusercontent.com/39112974/52773247-6dca8e00-3032-11e9-86b0-184b41528c8e.jpg)

Airbnb.com
![airbnb](https://user-images.githubusercontent.com/39112974/52773265-7327d880-3032-11e9-9627-612338009920.PNG)

Medium.com
![medium](https://user-images.githubusercontent.com/39112974/52773274-77ec8c80-3032-11e9-90d3-115d47e05343.PNG)

**Comment by buckwierd** [comment]
I'll deal with this asap.

**Comment by buckwierd** [comment]
"text-align: justify;" was replaced with  "text-align: inherit;"

@lcoenen feel free to close the issue after pushing to master. Was pushed under 4-adjust-the-static-centent

**Comment by lcoenen** [comment]
The change have been pushed to `staging`. Could you confirm that the change are ok and that everything is working before I push it to `master`?

**Comment by RohrerHope** [comment]
I'm looking at https://whichost-frontend-staging.herokuapp.com/ and justification is still there.

**Comment by RohrerHope** [comment]
Looking okay on staging. Justification is gone.

**Comment by lcoenen** [comment]
Ok guys, we will merge to `master` tomorrow after checking that everything is ok.

**Comment by lcoenen** [comment]
This will be pushed to Master
