### ISSUE TITLE
Whichost corporation 2019 on mobile footer is off

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#61]
The mobile footer, on the left where we have the corporation and the year 2019, that text is off.

![footer on mobile](https://user-images.githubusercontent.com/39112974/52773488-efbab700-3032-11e9-8e6f-314b90f9c669.PNG)

**Comment by buckwierd** [comment]
On my phone the footer is showing up correctly in one line. I guess it's related to the screen resolution. If this is the case, we'll have to find the best solution for the most common resolutions. I believe that we can't satisfy every single resolution with so many mobile devices out there. We'll see.

**Comment by RohrerHope** [comment]
If it's a matter of screen size then there's not much we can do there.
