### ISSUE TITLE
Mobile main logo is sauna

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#62]
This has been mentioned more than once before but it seems nobody actually created an issue for it.

So here it is.

Please change the sauna logo with the Whichost one, the orange one.

![mobile main logo](https://user-images.githubusercontent.com/39112974/52773558-27296380-3033-11e9-9df8-7632135971c2.PNG)

**Comment by RohrerHope** [comment]
@lcoenen 

This was reported as urgent and the SVG was generated, as far as I understand.

What's the status with this issue?

**Comment by lcoenen** [comment]
This have been fixed.
