### ISSUE TITLE
Change colour of button to request booking

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#63]
That green is off is not at all related to our brand. Please let's change that.

### Here is the button as we see it now:

![request to book button green](https://user-images.githubusercontent.com/39112974/52773855-d5350d80-3033-11e9-8020-90c86c73b4a9.jpg)

### And here is with our beautiful orange colour

![request to book button orange](https://user-images.githubusercontent.com/39112974/52773881-e0883900-3033-11e9-8235-6bf0cbf2a080.jpg)

Thanks 😄

**Comment by buckwierd** [comment]
I'll deal with this and it should be done by Friday.

**Comment by RohrerHope** [comment]
@buckwierd 

Please take care of all the green buttons we have. There are other buttons that have the same green. Log in button is another example.

**Comment by RohrerHope** [comment]
The element for the booking button is

.ListingPage__bookButton__2IVbZ

This element is being forced to the green colour, meaning if we remove that instruction the button will go to our orange.

![screen shot 2019-02-17 at 08 49 55](https://user-images.githubusercontent.com/39112974/52910556-065e4980-3291-11e9-91b1-ed29ae33cab9.jpg)

![screen shot 2019-02-17 at 08 50 15](https://user-images.githubusercontent.com/39112974/52910559-11b17500-3291-11e9-9fcd-7d70ed3e3605.jpg)

The green colour they use for the button is HEX #2ecc71 

There is also a hover effect on that button, so when we edit the button colour, we need to manage the hover colour.

![screen shot 2019-02-17 at 08 51 43](https://user-images.githubusercontent.com/39112974/52910572-48878b00-3291-11e9-924a-7ddd0714d279.jpg)

The hover colour they are using is HEX #239954

**Comment by buckwierd** [comment]
Colors are managed centralised over the "color" css file. Now that issue #79 was fixed, this one should automatically be fixed.

**Comment by buckwierd** [comment]
Closing
