### ISSUE TITLE
Search text inside search field to indicate location

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#64]
The search text we have now inside the search box placeholder says "Search pubs..." when it actually doesn't do that.

That search field is for location, not for pubs, and we need to clarify that to our users.

### Here is how it looks now

![search text](https://user-images.githubusercontent.com/39112974/52774035-48d71a80-3034-11e9-9ef7-14ee253cb886.jpg)

### Here is my proposal

![search text location](https://user-images.githubusercontent.com/39112974/52774138-8340b780-3034-11e9-8af2-f5d478c6e43d.jpg)

My proposal is for the placeholder to say "Enter location..."

**Comment by buckwierd** [comment]
I'll deal with this and it should be done by Friday.

**Comment by lcoenen** [comment]
This have been done and pushed to `master`
