### ISSUE TITLE
Cookies URL takes to nothing related to our Cookie policy

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#65]
![cookie policy](https://user-images.githubusercontent.com/39112974/52774332-dadf2300-3034-11e9-93fb-54632686a3ec.jpg)

That URL takes to: https://cookiesandyou.com/

Our Cookie policy URL is: https://info.whichost.com/eng/legal#cookies-section

**Please change this today, asap!**

**Comment by buckwierd** [comment]
I'll deal with this one and should be done by Friday.

**Comment by lcoenen** [comment]
This have been fixed and pushed to `master` and `staging`.
