### ISSUE TITLE
Remove deals from the Pubs footer

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#66]
Until we actually have deals for the publicans, let's please remove the "Deals for you" from the Pubs section on the footer.

![web footer pubs deals](https://user-images.githubusercontent.com/39112974/52774560-6658b400-3035-11e9-9757-d22d71427edc.jpg)

**Comment by buckwierd** [comment]
I'll deal with this and should be removed by Friday,

**Comment by lcoenen** [comment]
This have been fixed and pushed to `master` and `staging`.
