### ISSUE TITLE
Background main image is low quality

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#67]
The main image background we have on the platform is of low quality. You can clearly see that it's pixelated.

I'm attaching a screenshot here, but don't know if the screenshot will allow you to see the pixels. Please just access the website and you'll see the pixels.

![background image low quality](https://user-images.githubusercontent.com/39112974/52774741-df580b80-3035-11e9-91a3-bbc52e48efa8.jpg)

Below is a copy of the original image in a darker mode. It's 3MB so, please adjust its weight before using it :) 

https://drive.google.com/file/d/1ZkEt7EQ1UIqhzXnjbIw9fILhTv1PQRpU/view?usp=sharing

**Comment by buckwierd** [comment]
I don't know what you see, but on my screen everything looks fine. Maybe you can show us this on Friday @RohrerHope

**Comment by lcoenen** [comment]
Everything looks fine on my side too.

**Comment by RohrerHope** [comment]
As we talked during our meeting, the image is pixelated.

Please update with the image I provided above, in the description of the issue.

Thanks 😄
