### ISSUE TITLE
URLs inside the pub description are not detected as such

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#68]
In the Go platform, all URLs inside the pub's description were detected as such and so they behave like so, allowing users to click on them and it would open in a new tab.

This is not working with Flex, as you can see from the screenshot below.

![url not detected](https://user-images.githubusercontent.com/39112974/52775283-31e5f780-3037-11e9-83ef-d204ba5374a4.jpg)

All URLs inside a pub's description should be detected as such and users should be able to easily click on them. For now, they have to select, copy, open a new tab, paste and execute.

**Comment by lcoenen** [comment]
This is non-trivial and will require work.

**Comment by lcoenen** [comment]
This can be done using https://www.npmjs.com/package/react-linkify

**Comment by lcoenen** [comment]
This have been fixed and pushed to `staging`
