### ISSUE TITLE
Stripe is getting not so useful information about who is who in the transaction

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#70]
As you can see from the screenshot of the email received from Stripe, the information from the transaction is gibberish. The only thing I can understand from it is the €9 and the default text from the Striple email template. Other than that, we can't understand anything from that email.

With Go we had proper information, detail about who paid, the proper information was being shared.

![stripe payment notification](https://user-images.githubusercontent.com/39112974/52781026-7a0b1700-3043-11e9-8e8e-8e7419270e70.jpg)

**Comment by lcoenen** [comment]
It's something that have to do with the Stripe account. Not on the frontend.

**Comment by lcoenen** [comment]
An email have been sent to whichost.com about this issue.

**Comment by lcoenen** [comment]
![image](https://user-images.githubusercontent.com/1237971/52809860-27544e00-3089-11e9-86d8-393771665e45.png)
Here is the answer from Sharetribe. Having no example how how Go was working, I am unable to answer to this email. @RohrerHope

**Comment by RohrerHope** [comment]
@lcoenen 

I just looked at the previous payments we received through Go platform and they look the same.

That's my bad.

It seems there is no issue here.

My concern was raised because I want to make sure Stripe and Sharetribe are communicating properly.
