### ISSUE TITLE
Add "Help" to the main menu

### ISSUE THREAD

**Issue by buckwierd** [Whichost/frontend#71]
As it is common practice (Airbnb, Stripe, Gaest etc.) for the users to find help as quick and easy as possible, the help center will also be placed in the main menu as "Help", right after "Add your pub".

**Comment by buckwierd** [comment]
As this is JS, Loic needs to take a look at it.

@lcoenen Can you please add a new main menu item called "Help" with this link behind "https://info.whichost.com/eng/faq"?

The items will have the following order from left to right:
+Add your Pub | Help | Sign up | Login

**Comment by buckwierd** [comment]
Any update on this @lcoenen?

**Comment by buckwierd** [comment]
@lcoenen what's the status with this one? Can I do anything to assist you?

**Comment by lcoenen** [comment]
I'll do that in an hour.

**Comment by RohrerHope** [comment]
Approved in staging 👍

**Comment by buckwierd** [comment]
@lcoenen please add `target="_blank"` to the new help button in the main menu, otherwise the visitor has no easy chance to get back to the main platform. Thanks.

**Comment by lcoenen** [comment]
I do it, but this is not good practice. Opening new tabs is wrong UX https://ux.stackexchange.com/questions/5397/whats-your-take-on-target-blank.

**Comment by lcoenen** [comment]
This is only temporary and will be discarded as soon as we get share tribe.

**Comment by buckwierd** [comment]
Of course it’s bad UX but we have no other solution for the moment, due to Squarespace. So as you said, this will be reverted as soon as we go live with the new help center 😊
Thanks.
