### ISSUE TITLE
Whichost logo in footer not a PNG

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#81]
![screen shot 2019-02-16 at 14 47 55](https://user-images.githubusercontent.com/39112974/52901309-e891d580-31f9-11e9-8f45-757142eee743.jpg)

The white background of the image can be seen. This has been reported more than once.

**Please, change this image to a PNG, with a transparent background.**

**Comment by lcoenen** [comment]
The change have been pushed to `staging`.
