### ISSUE TITLE
Number of pubs on the map

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#82]
![screen shot 2019-02-16 at 14 50 31](https://user-images.githubusercontent.com/39112974/52901333-458d8b80-31fa-11e9-9e6c-1e8fcacb7891.jpg)

This is what you see when you click on Browse pubs.

The map is not showing the reality of the pubs' distribution we have.

Can we fix this so that it shows more pubs in other locations? Dublin, Galway and other locations we have.

This is about setting expectations to users when visiting our site and they see this map which shows only one location with pubs.

**Comment by lcoenen** [comment]
The truth is it's just charging the first few last pubs it have been added in the database. The issue is the same as #83. 

I guess I could figure out something but that will be a hack and non-trivial.

**Comment by RohrerHope** [comment]
Sounds good.

Let's see what we can do with  the map and the pubs shown there.
