### ISSUE TITLE
www.whichost.com/claim redirect to nowhere

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#84]
The L description contains links to www.whichost.com/claim, which redirect nowhere.

A redirection will be established.

**Comment by lcoenen** [comment]
This should be fixed. The change have been pushed to `master`.

**Comment by buckwierd** [comment]
@lcoenen when I try to open www.whichost.com I'm being forwarded to https://www.whichost.com/claim/

This means that now no one can open the marketplace platform :D

**Comment by buckwierd** [comment]
@lcoenen can you please fix it as urgent?
@RohrerHope in case Loic is sleeping, can you maybe remove the forwarding, if this is something that you know hiw?

**Comment by lcoenen** [comment]
Ugh on it

**Comment by lcoenen** [comment]
Building

**Comment by lcoenen** [comment]
The change have been pushed to `master`
