### ISSUE TITLE
Links in transaction emails still have market.whichost.com

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#89]
Please guys, update all links in the automatic emails we are sending.

I'm trying to update an email address of a user and it's providing me an URL for market.whichost.com.

![link in emails still say market](https://user-images.githubusercontent.com/39112974/53169173-71cb5280-35d4-11e9-985f-bbf849a8cbf5.jpg)

**Comment by RohrerHope** [comment]
Solved. Changed in Flex console.

**Comment by buckwierd** [comment]
Reopening as we might have to also change the transaction email templates that are not shown in the console.

**Comment by buckwierd** [comment]
I’ll deal with it no later than this weekend.

**Comment by buckwierd** [comment]
This needs to be undone back to the initial state:
{marketplace.url}

**Comment by RohrerHope** [comment]
I've added the  }{marketplace.url}} to all email templates inside the console and used the Preview tool to test that they were all okay.

So the only ones missing are the templates that are not inside the console.

**Comment by buckwierd** [comment]
For the future if you see the tag “Radu on it” or any other tag win a name saying “on it” attached to the issue, please contact the respective person before taking ownership, to avoid double works being done.

**Comment by RohrerHope** [comment]
My bad. I missed the Radu on it label.

Won't happen again. 👍 

So the only templates missing to adapt are the ones not in the console.

**Comment by buckwierd** [comment]
@lcoenen issue fixed and pushed over branch #89 to staging. Feel free to close the issue after pushing to master.

**Comment by lcoenen** [comment]
Buckwierd, please don't call branch with a number. Use a more explicit branch name like `email-verification`. We will talk about the git flow tomorrow.
