### ISSUE TITLE
Improve the title of the optional message customers can send providers when booking

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#90]
This is how it looks now:

![say hello to your host](https://user-images.githubusercontent.com/39112974/53243335-67c25600-369f-11e9-8757-851f0c8b1739.jpg)

The title says: Say hello to your host • optional

I propose a change to improve that invitation. This is my proposal: Say hello to your host and let them know if you have any special request • optional

This will clarify to the customer that any special requests need to be entered in that message box, and it's not only to say hello. 😄

**Comment by RohrerHope** [comment]
This is how the proposal would look like

![say hello to your host proposal](https://user-images.githubusercontent.com/39112974/53243566-2ed6b100-36a0-11e9-81b7-7a2b197f6a80.jpg)

**Comment by buckwierd** [comment]
@lcoenen issue fixed and pushed over branch #90 to staging. Feel free to close the issue after pushing to master. Thanks!
