### ISSUE TITLE
Every pub is priced with 9 euro

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#91]
Right now every pubs are 9 euros, which adds a lot of noise and irrelevant informations when looking for a pub.

I am afraid it would deter people to book (entry fees), and is not really cosmetic...

![image](https://user-images.githubusercontent.com/1237971/53262004-6a3ba480-36cd-11e9-84c7-2241fdb89e2b.png)

**Comment by lcoenen** [comment]
The 9 EUR information will be removed from the Searching page, and the terms will be changed to "deposit".

**Comment by lcoenen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clarify the deposit policy](https://trello.com/c/fv9HY9B6/55-clarify-the-deposit-policy)

**Comment by lcoenen** [comment]
@buckwierd I was thinking we could replace the "9 EUR" carrets with a little pub icons. 

Here's the original code in `src/components/SearchMapPriceLabel/SearchMapPriceLabel.js`.

      <button className={classes} onClick={() => onListingClicked(currentListing)}>
        <div className={css.caretShadow} />
        <div className={priceLabelClasses}>{formattedPrice}</div>
        <div className={caretClasses} />
      </button>

Would you have a suggestion for a pub icon to put on the map? :)

**Comment by buckwierd** [comment]
@lcoenen I don't have a icon in mind but I believe that if you link the Google material icons to our platform, we'll be able to find a good icon. We will also use these icons for future platform upgrades, as they are very handy to use: https://material.io/tools/icons/?style=baseline

**Comment by lcoenen** [comment]
The change have been pushed to `staging`. @buckwierd @RohrerHope Could you tell me what do you think?

**Comment by lcoenen** [comment]
@buckwierd We decided to simply use the whichost logo :) 
![image](https://user-images.githubusercontent.com/1237971/53885479-bf54b000-4015-11e9-8bbd-48ab792f3399.png)
Of course that doesn't say anything about the icon library we should use.

**Comment by RohrerHope** [comment]
Love it ❤️

**Comment by buckwierd** [comment]
From what I can se here, it’s fine for me. I hope it’s not pixeled like the mobile version icon that you Loïc still have to update, by the way.

**Comment by lcoenen** [comment]
@buckwierd Please comment on the corresponding issue.

**Comment by lcoenen** [comment]
This have gone live, the issue can be closed.
