### ISSUE TITLE
First message is not clear about what Whichost is

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#93]
When first-time visitors fall into Whichost, they don't know clearly what we are all about.

This is what they see today:

![original message](https://user-images.githubusercontent.com/39112974/53297277-f526b700-3813-11e9-992d-71ab91daf86c.jpg)

The message: "The largest online community to book parties and celebrations."

If you've never heard of Whichost before, how would you know from that message that you can **find and book a pub for your next party**? That that's is our solution for you? You wouldn't know from what we are showing today.

Our message is vague and does not explain clearly what's the benefit for you. In the end, people buy for themselves, so they need to see what's in it for them.

So, before we launch our social media campaign to promote our birthday deal, we need to change that first line. Here is my proposal:

![proposal](https://user-images.githubusercontent.com/39112974/53297285-315a1780-3814-11e9-8b89-65e4f105067f.jpg)

Clear and to the point: "**Find and book pubs for your parties and celebrations.**"

Thanks 👍

**Comment by lcoenen** [comment]
Pushed on `staging`, could you check that everything is ok?

**Comment by RohrerHope** [comment]
Looking good at staging.
