### ISSUE TITLE
Attendance error messages improvement

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#95]
**In the case of parties that are too big**, the message has a major grammar error: you don't say "too much people", you say "too many people". Also, we ask them to contact support and we don't provide an easy way to do it.

Let's please use Grammarly and double check our English. This is not our first language, and at all times we have a responsibility to express ourselves properly. It impacts how people will perceive us as a company.

Please follow the image below to improve the message:

![too many people](https://user-images.githubusercontent.com/39112974/53866835-67ed1a80-3fea-11e9-9a46-693ecaa54916.png)

**In the case of parties that are too small**, please apply the same text size, colour and position as the image above, and make a small change to the text, from "...into a pub. ;)" to "...into the pub. ;)". Why? Because they have already chosen one. It's not any pub, it's the pub. 🤓 

Thanks 👍

**Comment by buckwierd** [comment]
Why should we give them the option to contact the Whichost support in cases like this? What’s the benefit that we can offer if they contact us instead of directly contacting the pub?

Shouldn’t we give them the option to “Write us a message” (to the L owner) so they can discuss the size of the party directly themselves?

**Comment by RohrerHope** [comment]
I was only following the original logic proposed in the error message and improving it. I don't mind if we change it or remove it.

I'm okay with that option.

**Comment by lcoenen** [comment]
Grammarly won't work on the code. That is what `staging` is for, to check those kind of things before it goes live.

**Comment by lcoenen** [comment]
Please tell me the exact message we're supposed to put then?

**Comment by RohrerHope** [comment]
Regarding Grammmarly, they have a Mac app and you can also use it on their web version. So when editing English text you can always double check there before, so we save the time of fixing those errors 👍 


Regarding the error message, you can put: "That's too many people. Write us a message if you need assistance."
