### ISSUE TITLE
Remove the lateral scroll in mobile view

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#98]
**The mobile version has a lateral scroll.** 

This is looking directly at the table:

![Screen Shot 2019-03-17 at 18 51 05](https://user-images.githubusercontent.com/39112974/54496371-6d017200-48e6-11e9-88d8-f1656390156d.jpg)

And this is the lateral scroll. Notice the menu at the top how it is to the left, which means we have a small lateral scroll to the right, most probably caused by the table I believe, because that scroll is not in the "What's this" page.

![Screen Shot 2019-03-17 at 18 51 13](https://user-images.githubusercontent.com/39112974/54496374-7d195180-48e6-11e9-8439-d050046b963a.jpg)

**Comment by buckwierd** [comment]
No fix from my side at the moment as it takes time to investigate this issue. Will deal with it after we fixed the other more important issues.

**Comment by buckwierd** [comment]
I believe it's related to a padding within a section with `width: 100%;`. If you add padding to something with width set to 100% it will go outside the parent. Will continue looking into it.

**Comment by scottyzen** [comment]
Fixed. https://github.com/Whichost/frontend/pull/253
